.github/workflows/deploy.yml, .github/workflows/test.yml, tox.ini
First attempt at using GitHub actions. I've decided to run the tests (lint, test, docs) with tox in the CI. This is different from what we were doing on GitLab but this seems more natural since locally we run the tests with tox.
The biggest difference so far with our previous setting is that there doesn't seem to be an integrated way to feed the tests and coverage reports to GitHub actions. I've looked at some popular repos and couldn't find anything interesting, it seems that in most cases the reports are just not handled in a specific way (one just has to go to the workflow logs to find some more details if need be). Some alternatives though:
* This action that adds a bot which can publish junit test reports: https://github.com/marketplace/actions/publish-unit-test-results
* The github …
=> CI with GitHub actions

docs/conf.py
=> Display star number instead of watch number in the docs

.github/workflows/deploy.yml, .github/workflows/test.yml, tox.ini
`allowlist_externals = /bin/bash` in `tox.ini` was too restrictive and raised a warning (`/bin/bash` is used in local tests, but `/usr/bin/bash` in github actions).
See https://tox.readthedocs.io/en/latest/config.html#conf-allowlist_externals
Also added `pip install sphinx` to have rst2html.py utility available)
=> chore: tox fix for pypi

docker-compose.yml, docker/stac-browser.dockerfile
I had to change `stac:5000` by `localhost:5000` for stac-browser because of an issue with CORS in my environment:
=> fix: cors issue with docker-compose

docs/_static/custom.css, docs/conf.py
Fixes #193 
Making the sidebar always visible had the side effect of hiding the bottom of it since it is not scrollable by default.
This workaround from a SO answer([here](https://stackoverflow.com/questions/57031848/sphinx-alabaster-theme-scroll-inside-of-fixed-sidebar/57040610)) solved the problem by making the sidebar scrollable.
Now the sidebar is always visible and a scroll bar appears when it becomes too big to fit into a single page.
=> docs: fixed and scrollable sidebar

.github/workflows/test.yml, eodag/api/core.py, tests/test_config.py, tox.ini
Fixes #162 
Small updates required to add Windows support:
* `tempfile.NamedTemporaryFile` doesn't work exactly the same on Windows: https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
* One test expected a Unix "/tmp" directory
* The template path for the locations shapefile expected a `/` path separator
The tests now also run on Windows.
=> Add Windows support

eodag/api/core.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, eodag/resources/stac_provider.yml, tests/context.py, tests/test_end_to_end.py, tests/units/test_core.py
Fixes #191 
Two new methods for `EODataAccessGateWay`:
* `search_iter_page`: to iterate over the pages of a products search
* `search_all`: to get all the products matching some search criteria -> it uses `seach_iter_page` internally to iterate over all the pages that return products
`search_all` tries to be a little smarter than `search_iter_page` or  `search`, in the sense that it tries to minimize the number of requests made. It makes use of an internal parameter `max_items_per_page` configured per provider (see `providers.yml`). 8 providers have such a parameter configured, I have found these values either in their documentation (and checked it) or by trial and error. If this internal parameter isn't set, a default value of 50 is used. I chose it because it's the lowest one between …
=> feat: add two new methods to search for products, search_iter_page and search_all

eodag/api/core.py, tests/units/test_core.py
Fixes #174 
The catalog we use is small so this should have no effect at all in terms of performance. However it should help to make sure that the product type returned by `guess_product_type` is really the best match among all the products that matched each criteria.
Depends on #190
=> Whoosh search returns now all the matching products

CHANGES.rst, eodag/cli.py, eodag/utils/logging.py
Fixes #197 
```diff
-def setup_logging(**kwargs):
+def setup_logging(verbose):
"""Define logging level
-    :param kwargs: Accepted Keyword arguments:
-                    verbose=0-3 logging level (None to max)
-    :type kwargs: dict
+    :param verbose: Accepted values:
+
+                    * 0: no logging
+                    * 1 or 2: INFO level
+                    * 3: DEBUG level
+    :type verbose: int
"""
```
=> fix: more explicit signature for setup_logging

README.rst, docs/use.rst, eodag/cli.py, tests/test_cli.py
Fixes #202 
I had to remove the default value of `--items` at the "click" level, since it's not used in the same way by `search` and `search_all`. Instead it is set inside the CLI search function. I have adapted the "help" of `--items` so that it still displays the default value (as of now: 20).
Depends on #190
=> Add a --all option to the search command to search for all the products

eodag/plugins/apis/usgs.py, eodag/plugins/download/base.py, eodag/plugins/manager.py, eodag/resources/providers.yml, setup.py, tests/test_end_to_end.py, tests/units/test_core.py
fixes #147 
`UsgsApi` uses latest [usgs v0.3.0](https://github.com/kapadia/usgs/) for both search and download. Previously it was just used to perform search. Download was done on [Google Cloud](https://cloud.google.com/storage/docs/public-datasets/landsat).
Previous [usgs](https://github.com/kapadia/usgs/) versions used a deprecated API. It now uses [Machine-to-Machine API](https://m2m.cr.usgs.gov/).
=> fix: usgs plugin

tests/resources/stac/country/FRA/year/2018/items/S2A_MSIL1C_20181231T141041_N0207_R110_T21NYF_20181231T155050/S2A_MSIL1C_20181231T141041_N0207_R110_T21NYF_20181231T155050.json, tests/resources/stac/country/FRA/year/2018/items/S2A_MSIL1C_20181231T141041_N0207_R110_T22NBJ_20181231T155050/S2A_MSIL1C_20181231T141041_N0207_R110_T22NBJ_20181231T155050.json, tests/resources/stac/country/GBR/year/2019/items/S2A_MSIL1C_20191231T112451_N0208_R037_T30UUD_20191231T115143/S2A_MSIL1C_20191231T112451_N0208_R037_T30UUD_20191231T115143.json, tests/resources/stac/country/GBR/year/2019/items/S2A_MSIL1C_20191231T112451_N0208_R037_T30VVH_20191231T115143/S2A_MSIL1C_20191231T112451_N0208_R037_T30VVH_20191231T115143.json
Root link in tests stac items was not valid and made pystac raise an exception.
This link was not checked until `pystac v0.5.6` but now it is
=> test: fixes root link in stac static resources

eodag/__init__.py
with `from eodag import setup_logging` since we use it in most tutorials.
=> Make setup_logging easier to import

eodag/utils/notebook.py
Fixes #222 
I quickly tried to add a small test for this but it would really need to be run in an ipython shell, since `IPython.display.display` always returns None if executed outside such a context, while in an ipython shell it would return the handle (asked for with `display_id=True`).
Instead I've tested it manually and it worked fine.
=> fix: do not use ipywidgets for the Notebookwidgets representation

eodag/api/core.py, eodag/plugins/manager.py
This PR is a proposal to fix the issue https://github.com/CS-SI/eodag/issues/234.
It would nice we can add to user configuration files our own settings of providers loaded via plugins. 
This minor change allows we configure all providers in the same way, not taking care if they are implemented in the code base or via plugins.
=> [Bugfix #234]: Error loading user config files with settings of providers loaded via plugins

eodag/api/core.py, eodag/api/product/_product.py, eodag/plugins/apis/base.py, eodag/plugins/apis/usgs.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/rest/utils.py, eodag/utils/__init__.py, tests/context.py, tests/test_cli.py, tests/test_end_to_end.py, tests/units/test_eoproduct.py, tests/units/test_utils.py
Fixes #232 
* The paths returned by either `EODataAccessGataway.download`, `EODataAccessGataway.download_all` or `EOProduct.download` are all system file paths (e.g. "/tmp/product.zip").
* The `location` attribute of an `EOProduct` once downloaded is updated to the file URI representation of its location (e.g. "file:///tmp/product.zip")
I was tempted to implement the logic above directly into `EOProduct.download` and ask/update each plugin to call that method to download a product. I saw however that the sentinelsat plugin was using a `download_all` method provided by the sentinelsat package, it wouldn't have been able to call `EOProduct.download`. So the contract is that each plugin is responsible for implementing the logic above, and more generally the logic we use when a file is …
=> Homogenize inconsistent paths returned by the download methods

eodag/utils/__init__.py
I saw a lot of warnings popping up while running tox. This was due to the _deprecated decorator not resetting properly the warning filters.
=> _deprecated wasn't resetting the warning filters correctly

eodag/api/product/_product.py
=> Clearer docstring for get_quicklook about the default filename and the output folder

eodag/api/core.py
Fixes #240 
Thanks @sbrunato for the snippet!
I could test this by running eodag with python 3.8 first (which introduced a new pickle protocol) and then python 3.7, the error was properly caught and the index recreated.
=> Recreate whoosh index when unsupported pickle protocol

eodag/api/core.py, eodag/api/product/metadata_mapping.py, eodag/cli.py, eodag/resources/providers.yml, eodag/utils/__init__.py, tests/context.py, tests/units/test_metadata_mapping.py, tests/units/test_utils.py
Fixes #227 
I used the function `datutil.parser.isoparse` to parse user input dates, which should cover most cases.
=> ISO 8601 format accepted everywhere

eodag/api/core.py, eodag/resources/providers.yml, tests/units/test_core.py
Fixes #265 
Also adds `max_items_per_page` for aws_eos and earth search.
=> Add a warning when `items_per_page` is higher than `max_items_per_page`

eodag/resources/providers.yml
=> fix: Earth Search uses next_page_url_tpl to get the next page in search_iter_page

README.rst, eodag/api/product/_product.py, eodag/cli.py
This PR is a proposal of implementation for https://github.com/CS-SI/eodag/issues/264.
It works here for me, I hope it can be useful in some manner for your future implementation.
Thanks for developing this amazing software.
NOTE:
I have not implemented this code defining a `get_quicklook` command because of parser internally changes the parameter name to `get-quicklook`. I was not able to define the necessary extra setting.
=> New optional "quicklooks" flag in "download" command

setup.py, tests/test_cli.py
- Fixes 2 tests failing when using click v8.0.0 https://github.com/CS-SI/eodag/runs/2598488725: 
- One due to options error message reformatting, see https://github.com/pallets/click/commit/8d49e146ab8c2312e7917bb7c3f8abf01b8b55bf#diff-948f9e0cc733616a6b18aa152ac6703e819fec61dd752d1efa40e5736c3bdce7R423
- Another one caused by wrong type args (`int` instead of `str`) passed to CLI cruncher in tests. This was ignored with `click<8.0`
- Updates `nbsphinx` following `Jinja2` update that broke the pinned version, see https://github.com/spatialaudio/nbsphinx/issues/563
=> fix: CI failure following deps upgrade

eodag/utils/logging.py
Add `get_logging_verbose()` function to be able to get eodag current logging settings (needed to fix https://github.com/CS-SI/eodag-sentinelsat/issues/9)
=> feat: get_logging_verbose function added

tests/context.py, tests/units/test_utils.py
Unit tests for `eodag.utils.ProgressCallback`, following GH-276
=> test: ProgressCallback unit tests

README.rst, docs/notebooks/intro_notebooks.ipynb
Fixes GH-286
Links to documentation are now on https://eodag.readthedocs.io/en/latest/ instead of https://eodag.readthedocs.io/en/stable/
=> docs: default links to readthedocs latest version

eodag/utils/__init__.py, tests/context.py, tests/units/test_utils.py
Fixes GH-278
`provider.search` configuration can now be dynamically updated from queryable parameters (`list`) to non-queryable (`str`) and vice-versa
=> fix: conf updatable from non-queryable params to queryable

eodag/plugins/download/base.py, tests/test_end_to_end.py
=> fix: paths when downloading and extracting again with archive depth

eodag/config.py
Trying to load misconfigured provider from user configuration might result in the following error:
```py
from eodag import EODataAccessGateway
dag = EODataAccessGateway()
2021-06-08 16:48:18,555-15s eodag.config                     [INFO    ] wekeo: unknown provider found in user conf, trying to use provided configuration
Traceback (most recent call last):
dag = EODataAccessGateway()
File "/home/sylvain/workspace/eodag/eodag/api/core.py", line 107, in __init__
override_config_from_file(self.providers_config, user_conf_file_path)
File "/home/sylvain/workspace/eodag/eodag/config.py", line 268, in override_config_from_file
override_config_from_mapping(config, config_in_file)
File "/home/sylvain/workspace/eodag/eodag/config.py", line 333, in override_config_from_mapping
config[provider] = …
```
=> fix: ignore and log misconfigured provider from user conf

CHANGES.rst, docs/api_reference/utils.rst, docs/conf.py, docs/index.rst
- Changelog update
- Eodag version is now displayed in the documentation title, which will help to identify which version is linked to a given documentation ([latest](https://eodag.readthedocs.io/en/latest) or [stable](https://eodag.readthedocs.io/en/stable)), see #297
- Changes to readthedocs webhook on github:
- disabled: `Branch or tag creation`, `Branch or tag deletion`, `Pushes`
- enabled: `Releases `
(only `Pull requests` and `Releases ` are kept checked)
=> docs: documentation update before v2.3.0b1 release

eodag/api/core.py
fixes #305 
Reload plugins (and check configuration) after providers settings update from user configuration file
=> fix: reload plugins after providers settings update from user conf

eodag/utils/notebook.py
New function `check_notebook()` used instead of `check_ipython()` when running `NotebookWidgets.display_html()` in order to prevent HTML rendering in ipython shell.
=> fix: prevent NotebookWidgets.display_html in ipython shell

docker/stac-browser.dockerfile
Fixes #313 
Use `node:lts-buster-slim` instead of `node:lts-jessie-slim` to have `Node.js >= 12`.
Update `stac-browser` `npm build` command,  see [stac-browser v2.0.0-rc.3 changelog](https://github.com/radiantearth/stac-browser/releases/tag/v2.0.0-rc.3)
=> fix: dockerfile update for stac-browser v2.0

setup.py
Adds new `notebook` extra dependency which will install  `ipywidgets` through `tqdm[notebook]`:
```sh
pip install eodag[notebook]
```
Please note that `pip >= 20.2` will be needed to install this extra as `tqdm` is already in `install_requires`, see https://github.com/pypa/pip/issues/988
=> feat: new notebook extra dependency

eodag/plugins/download/aws.py
Expose AWS authentication settings to be used as rasterio session attributes in `eodag-cube`
=> feat: expose aws env settings in AwsDownload

eodag/api/core.py, tests/test_end_to_end.py
fixes #311 
Guess and set `product.product_type` when searching by id, using `guess_product_type()` with `product.properties`
=> fix: guess and set product_type when searching by id

eodag/utils/stac_reader.py, setup.py, tests/integration/test_search_stac_static.py, tests/units/test_stac_reader.py
Fixes [CI failure](https://github.com/CS-SI/eodag/runs/3101522106) after [pystac v1.0](https://github.com/stac-utils/pystac/releases) update.
Note that [single-file-stac](https://github.com/stac-extensions/single-file-stac) has been removed from `pystac` as the extension is being rethought
=> fix: pystac v1.0 update

README.rst, docker-compose.yml, docker/run-stac-server.sh, docs/stac_rest.rst
`EODAG_LOGGING` environment variable can be used with `docker-compose up` to increase `eodag` logging level in `stac-server`.
It accepts values: 1, 2, or 3 for maximum level.
Example:
```sh
EODAG_LOGGING=3 docker-compose up
```
=> feat: configurable eodag logging in docker stac-server

.gitattributes, docker/run-stac-server.sh, docker/stac-server.dockerfile
fixes #322 
Adds a `.gitattributes` file containing `* -text` to prevent `git` from normalizing EOL when running on windows.
Also some minor reformatting.
=> fix: prevent eol auto changes on windows causing docker crashes

eodag/api/core.py
Fixes #325 
When searching for a given product, it is now possible to use extra search args, like the `productType` to help finding the right product:
```py
products, _ = dag.search(
id="S1A_IW_GRDH_1SDV_20210202T060100_20210202T060125_036407_0445F3_EDB8", 
provider="creodias"
)
products, _ = dag.search(
id="S1A_IW_GRDH_1SDV_20210202T060100_20210202T060125_036407_0445F3_EDB8", 
provider="creodias", 
productType="S1_SAR_GRD"
)
```
=> feat: enable kwargs when searching by id

eodag/api/core.py
Fixes #328 
This shortens `search_all` preparation, preventing running `_prepare_search()` and the associated logging twice
=> fix: do not prepare search_all twice

eodag/plugins/manager.py, eodag/plugins/search/qssearch.py
Removed `StopIteration` usage following [PEP 479](https://www.python.org/dev/peps/pep-0479/) recommendations
=> fix: remove StopIteration usage following PEP-479

eodag/api/product/_product.py
This PR aims to solve the issue of getting overviews for ONDA provider:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3c773c92be6c> in <module>
1 workspace = "eodag_workspace_overview"
2 quicklooks_dir = os.path.join(workspace, "quicklooks")
----> 3 product.get_quicklook(base_dir=quicklooks_dir)
~/eodag/eodag/api/product/_product.py in get_quicklook(self, filename, base_dir, progress_callback)
399             ):
400                 with open(quicklook_file, "wb") as fd:
--> 401                     fd.write(self.properties["quicklook"])
402                 return quicklook_file
403 
TypeError: a bytes-like object is required, not 'str'
```
The quicklook in this case is a [base64](https://gist.github.com/drnextgis/e494a1150fffda1189c80362312 …
=> Fix get_quicklook method for onda provider

eodag/utils/__init__.py
Fixes #343 
In ProgressCallback:
- Rename `__call__` parameter `current_size` to `increment`.
- Inside of `__call__`, add condition to the call of the reset method in order to prevent resetting the progress bar each time.
=> Fix progress callback

eodag/plugins/download/s3rest.py, eodag/utils/__init__.py
fixes #349 
When trying to download `S2_MSI_L2A` products, `mundi` returned unwanted percent-encoded keys, making its parsing fail
=> fix: unwanted percent-encoded keys with mundi S2_MSI_L2A

.github/workflows/test.yml, tests/__init__.py
CI fails for `py3.9.8` on `windows-latest` (`pathlib` issue).
Skip this version for `py3.9.9` which is already available
=> test: prevent failing actions for windows py3.9.8

docs/getting_started_guide/configure.rst, docs/notebooks/api_user_guide/1_overview.ipynb, docs/notebooks/api_user_guide/7_download.ipynb, eodag/config.py, eodag/plugins/download/base.py, eodag/resources/user_conf_template.yml, tests/units/test_eoproduct.py
Closes #144
Adds deletion of the product's archive after download. Also, the extraction of the product's archive is done inside of a temporary folder to avoid pollution of the download directory with incomplete products if extraction was canceled.
Also, fix some tests and add a test to check this new feature.
=> Automatic archive deletion

docs/_static/params_mapping_extra.csv, docs/_static/params_mapping_opensearch.csv, eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, eodag/resources/stac_provider.yml, tests/units/test_metadata_mapping.py
fixes #354 
Implements STAC API `Query` fragment.
*Note that it is planned to be deprecated and be replaced with `Filter` fragment. But for the moment STAC providers `earth_search` and `usgs_satapi_aws` are using it (`astraea_eod` do not use any of the 2), so we go for `Query` fragment and will update to `Filter` when needed.*
=> feat: stac api query fragment usage

docs/api_reference/utils.rst, eodag/api/core.py, eodag/api/product/_product.py, eodag/utils/__init__.py, tests/__init__.py, tests/integration/test_core_search_results.py, tests/units/test_eoproduct.py, tests/units/test_utils.py
Closes #121.
- For `download_all`: callback is done inside the `download_all` method of `eodag.plugins.download.base.Download`, because its children  `download_all` methods delegates to `super()`. Every class inheriting `Download` will get this callback behavior when calling `super().download_all(...)`.
- For `download`: the callback is done after the download is finished, inside the `download` method of `EOProduct`. i wanted to use it too inside of the `Download` class but its children don't call its `download` method. I could add the callback inside every children `download` method, but some of them have a lot or `return`, it is not really efficient.
As of now, callback is inside of `Download` for `download_all`, and in `EOProduct` for `download`.
While it is working, it's not clean. …
=> Download callback

docs/api_reference/core.rst, docs/notebooks/api_user_guide/4_search.ipynb, eodag/api/core.py, eodag/resources/product_types.yml, eodag/utils/__init__.py, tests/units/test_core.py
- new field `keywords` added in product types configuration file `product_types.yml`. Field is case insensitive and ignores `-` or `_` characters
- `whoosh` product types search index is now rebuilt when `product_types.yml` MD5 checksum changes instead of eodag version.
This enables the following behavior:
```py
>>> from eodag import EODataAccessGateway
>>> dag = EODataAccessGateway()
>>> dag.guess_product_type(keywords="sentinel* SAFE")
['S1_SAR_GRD', 'S1_SAR_OCN', 'S1_SAR_RAW', 'S1_SAR_SLC', 'S2_MSI_L1C', 'S2_MSI_L2A']
>>> dag.guess_product_type(keywords="landsat* Collection2")
['LANDSAT_C2L1', 'LANDSAT_C2L2ALB_BT', 'LANDSAT_C2L2ALB_SR', 'LANDSAT_C2L2ALB_ST', 'LANDSAT_C2L2ALB_TA', 'LANDSAT_C2L2_SR', 'LANDSAT_C2L2_ST']
>>> dag.guess_product_type(keywords="landsat* Collection2 L1") …
```
=> feat: keywords usage in product_types configuration

eodag/plugins/download/http.py
Alternative ways to fetch HTTP STAC assets informations (size, filename)
=> fix: alternative http assets infos fetch

eodag/api/core.py, tests/integration/test_search_stac_static.py
Guess `eoproduct.product_type` if missing using `eoproduct.properties`.
Needed by #364
=> feat: guess eoproduct.product_type from properties

eodag/resources/providers.yml
fixes #369 , disable `cloudCover` for RADAR product types in providers configuration (S1 and S3 SRAL).
Even if `cloudCover` is used as query paramater for these product types, it will be ignored and not sent in the query.
=> fix: disable cloudCover for RADAR product types

eodag/plugins/apis/usgs.py
Fixes an issue when downloading a product using usgs provider that raised:
```
eodag.utils.exceptions.NotAvailableError: No usgs request url was found for LC81680252017074LGN00
```
Solution:
In USGS API plugin, look for products in `download_request["data"]["availableDownloads"]` in addition of `download_request["data"]["preparingDownloads"]`.
=> fix: NotAvailableError using usgs api

setup.py
Fixes issue when running `tox -e docs`:
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' 
```
eodag documentation build depends on `sphinx` which depends on `jinja2` using `markupsafe`.
Temporary fix is to pin `markupsafe < 2.1.0`, see https://github.com/pallets/jinja/issues/1585 , https://github.com/pallets/jinja/issues/1587
=> fix: pin markupsafe for doc build

eodag/api/product/metadata_mapping.py, tests/test_cli.py, tests/units/test_core.py, tests/units/test_safe_build.py
Fixes cli verbose level in tests which kept progress bars disabled in further tests. 
These errors occurred when runing `pytest`:
```
========================================================= short test summary info ======================================================================
FAILED tests/units/test_utils.py::TestUtils::test_progresscallback_copy - AttributeError: 'ProgressCallback' object has no attribute 'unit'
FAILED tests/units/test_utils.py::TestUtils::test_progresscallback_disable - AssertionError: '50%' not found in ''
FAILED tests/units/test_utils.py::TestUtils::test_progresscallback_init - AttributeError: 'ProgressCallback' object has no attribute 'unit'
FAILED tests/units/test_utils.py::TestUtils::test_progresscallback_init_customize - AttributeError: …
```
=> test: cli verbose level fix in tests 

eodag/plugins/download/aws.py, eodag/resources/providers.yml, tests/units/test_search_plugins.py
fixes #402, answers [#404 ](https://github.com/CS-SI/eodag/discussions/404)
- handle missing files error during SAFE build 
- fixes issue in `productPath` property extraction regex for `earth_search` provider
=> fix: productPath regex for earth_search

eodag/api/core.py, eodag/resources/providers.yml, tests/test_end_to_end.py
- fixes `archive_depth` setting for `creodias`
- fixes `delete_archive` setting in `test_end_to_end_complete_peps()`
=> fix: creodias archive_depth and e2e complete test

tests/integration/test_config_ext_plugin.py, tests/integration/test_core_search_results.py, tests/integration/test_search_stac_static.py, tests/test_cli.py, tests/units/test_core.py
Use tmp dir as mocked home directory during tests. 
This will prevent conflicts with existing eodag configuration, or between tests running in parallel.
=> test: use tmp eodag conf dir

.github/workflows/test.yml
Triggers coverage reports publish GH action only for pull requests events (by default on opened, synchronize, or reopened, see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
=> ci: cov reports only for PR

.pre-commit-config.yaml, eodag/api/product/metadata_mapping.py, eodag/rest/server.py, tests/test_end_to_end.py, tests/units/test_eoproduct.py
- Updates pinned black version in pre-commit, fixes conflict with click v8.1.0:
```
ImportError: cannot import name '_unicodefun' from 'click'
```
See https://github.com/psf/black/issues/2964
- [`get_json()`](https://flask.palletsprojects.com/en/2.1.x/api/#flask.Request.get_json) method usage before content type is defined. Fixes error introduced with Flask v2.1.0:
```
werkzeug.exceptions.BadRequest: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
```
=> fix: update black and adapts json data handling to flask 2.1.0

eodag/api/core.py, eodag/api/product/_product.py, eodag/api/product/metadata_mapping.py, eodag/config.py, eodag/plugins/apis/base.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/s3rest.py, eodag/rest/stac.py
Close #385 
The type hints used for `**kwargs` arguments were not following [PEP 484](https://peps.python.org/pep-0484/#arbitrary-argument-lists-and-default-argument-values)
The type hint for `**kwargs` must document the type of the values, so if `kwargs` is of type `dict[str, int]` its type hint must be just `int`. Because **kwargs** will always be `dict[str, X]`, only X, the values types, must be given. This is why default value is `Any`, meaning `dict[str, Any]`
=> Fix type hint of kwargs

eodag/plugins/search/qssearch.py
fixes #439 
Includes all available metadata from onda search to search results
=> fix: get all available metadata for onda products

docs/_static/params_mapping_extra.csv, docs/_static/params_mapping_opensearch.csv, docs/add_provider.rst, docs/notebooks/api_user_guide/2_providers_products_available.ipynb, eodag/api/core.py, eodag/plugins/manager.py, eodag/resources/providers.yml, eodag/rest/stac.py, tests/integration/test_config_ext_plugin.py, tests/integration/test_core_search_results.py, tests/integration/test_search_stac_static.py, tests/test_cli.py, tests/test_config.py, tests/test_end_to_end.py, tests/units/test_core.py, tests/utils.py
- Adds a boolean (`need_auth`) to providers configuration to tell if it needs auth for search or not.
- During `EODataAccessGateway` init, removes from available providers list the ones without credentials needing auth for search
See #368
=> feat: prune providers without credentials needing auth for search

eodag/plugins/authentication/token.py, tests/units/test_auth_plugins.py
Using TokenAuth plugin:
- allow formatting in `auth_uri`, like `http://foo.bar?username={username}&password={password}`
- allow specifying headers for token post request
=> feat: allow headers and url formatting in TokenAuth

eodag/api/core.py
Fixes issue related to new `need_auth` settting with api plugins search (like usgs), leading to this error when performing search:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/sylvain/workspace/eodag/eodag/api/core.py", line 599, in search
search_kwargs = self._prepare_search(
File "/home/sylvain/workspace/eodag/eodag/api/core.py", line 1031, in _prepare_search
search_plugin.auth = auth_plugin.authenticate()
AttributeError: 'NoneType' object has no attribute 'authenticate'
```
=> fix: need_auth and api plugin search

docs/api_reference/searchresult.rst, docs/notebooks/api_user_guide/6_crunch.ipynb, eodag/api/search_result.py, tests/units/test_search_result.py
Close #215 
Changes made to the SearchResult class (https://github.com/CS-SI/eodag/pull/359) added an easier way  to filter-out OFFLINE products.
In the original issue, that kind of code did the trick:
```python
from eodag.plugins.crunch.filter_property import FilterProperty
dag.set_preferred_provider("peps")
prods, _ = dag.search(...)
online_prods = prods.crunch(FilterProperty({"storageStatus": "ONLINE", "operator": "eq"}))
dag.download_all(online_prods)
```
Currently, with the filters attached we can do:
```python
[...]
online_prods = prods.filter_property(storageStatus="ONLINE")
[...]
```
This PR simply creates an alternative, that seems like a basic filter.
```python
[...]
online_prods = prods.filter_online()
[...]
```
Another suggestion in the issue was to add a parameter to …
=> Online filter

docs/getting_started_guide/install.rst, setup.cfg
Fixes [error](https://github.com/CS-SI/eodag/runs/6856763522?check_suite_focus=true) with `pyproj` install on `python3.10`
```
Collecting pyproj
Downloading pyproj-3.2.1.tar.gz (213 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.3/213.3 KB 55.8 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
[end of output]
```
`owslib` latest release …
=> build: downgrade owslib with py310

.github/workflows/fetch.yml
Create a Pull Request instead of a new commit with newly discovered external product types configuration
=> fix: use PR in github action to update external product types reference

.github/workflows/fetch.yml
skip last commit summary when not needed in fetch product types : if there is nothing to commit, last commit shown is out of context
=> fix: skip commit summary when not needed in fetch product types ci

pyproject.toml, setup.py
Set `setuptools_scm` maximum version until #476 is fixed
=> build: setuptools_scm max version for py36

CHANGES.rst, eodag/resources/providers.yml, pyproject.toml, tests/units/test_search_plugins.py
fixes #479 
Issue caused by `jsonpath-ng.ext` `sub()` method returning no result if nothing is found to substitute. A PR is already opened to fix this behavior https://github.com/h2non/jsonpath-ng/pull/83
=> fix: jsonpath issue causing missing productPath property

eodag/api/core.py, eodag/api/product/metadata_mapping.py, tests/integration/test_core_config.py
Fixes metadata-mapping issues when updating a provider's configuration after having already searched on it:
```py
>>> from eodag import EODataAccessGateway
>>> dag = EODataAccessGateway()
>>> dag.set_preferred_provider("earth_search")
>>> dag.search()
([EOProduct(id=S2B_46XDG_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_46XDG_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_46XFF_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_47XMA_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_46XFF_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_47XMA_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_46XEG_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_46XEG_20220720_0_L2A, provider=earth_search), EOProduct(id=S2B_47XNA_20220720_0_L2A, …
```
=> fix: metadata-mapping with providers update

eodag/config.py, tests/context.py, tests/integration/test_core_config.py
Fixes missing plugin when added through a provider's config update, that did not have a plugin entry of this type configured yet
See test as example (`foo_provider` had no `auth` plugin configured before):
https://github.com/CS-SI/eodag/blob/a973a8d340710bfda2f67194a135ae8dcfe7ac81/tests/integration/test_core_config.py#L97-L110
=> fix: update provider with new plugin entry

eodag/resources/stac_provider.yml, tests/units/test_search_plugins.py
Allows STAC providers to return `None` as item geometry, and use `[-180, -90, 180, 90]` as default value
=> feat: allow empty geometry for stac providers

eodag/api/core.py, eodag/plugins/search/qssearch.py, tests/context.py, tests/integration/test_core_config.py
Fixes issue with `discover_product_types()` that did not use configured auth plugin to query on provider's endpoint
=> fix: discover_product_types auth

setup.cfg
Use temporarily `flask < 2.2.0` to prevent doctest error, see https://github.com/pallets/werkzeug/issues/2485
=> fix: pin flask version to prevent doctest error

eodag/config.py
Github pages usage to serve static [*external product types configuration* file](https://cs-si.github.io/eodag/eodag/resources/ext_product_types.json) (see [Product types discovery documentation](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/2_providers_products_available.html#Product-types-discovery))
=> feat: external product types conf on gh pages

docs/notebooks/api_user_guide/2_providers_products_available.ipynb, eodag/api/core.py, tests/units/test_core.py
For new system-wide providers (updated system `providers.yml`), launch product types discovery after having fetched external products types configuration:
If a new provider `foo`, is added by user in `{eodag_install_dir}/resources/providers.yml`, it will not be listed in the remote [`ext_product_types.json`](https://cs-si.github.io/eodag/eodag/resources/ext_product_types.json) which will trigger its product types discovery.
This behavior will also be the same when the providers configuration from eodag github `develop` branch differs from the user one.
See [product types discovery documentation](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/2_providers_products_available.html#Product-types-discovery) for more information
=> fix: discover product types for new default providers

eodag/api/product/_product.py, eodag/config.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/token.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/search/qssearch.py, tests/context.py, tests/integration/test_core_config.py, tests/test_config.py, tests/units/test_eoproduct.py, utils/params_mapping_to_csv.py
Use default timeouts for all requests methods calls:
- 5s for query/search
- 60s for stream/download (see #394)
=> fix: timeout set for all requests methods

setup.cfg
Updates update flask version limit after `flask v2.2.2` release, which fixes issue with doctest. 
See https://github.com/pallets/werkzeug/pull/2497.
Related to https://github.com/CS-SI/eodag/pull/492.
=> fix: update flask version limit

requirements-docs.txt
Fixes vulnerability raised by dependabot https://github.com/advisories/GHSA-9jmq-rx5f-8jwq
=> fix: update nbconvert

.github/workflows/test.yml, CONTRIBUTING.rst, pyproject.toml, setup.cfg, setup.py, tox.ini
fixes #476 
Drop support for `python3.6`, update setup and test files (reverts #477)
=> fix: drop support for python3.6

eodag/plugins/apis/cds.py, tests/units/test_apis_plugins.py
Handles `cdsapi` logging on eodag side until https://github.com/ecmwf/cdsapi/pull/47 is merged.
This prevents `cdsapi` logging settings to override other packages ones. Also these settings could not be updated once set.
=> fix: cdsapi logging

tests/units/test_download_plugins.py
The margin was too thin when comparing *download retry* counts in `test_plugins_download_http_retry_error_timeout()`.
Changes this margin to be sure that we cannot have a false test failure.
=> test: less restrictive comparison in download retry tests

eodag/plugins/apis/cds.py
Checks `len(logger.handlers)` instead of `logger.hasHandlers()` to check if if logger is set because [hasHadlers()](https://docs.python.org/3/library/logging.html#logging.Logger.hasHandlers) also iterates over parents
=> fix: cdsApi logging handler

eodag/plugins/download/aws.py, eodag/plugins/download/s3rest.py, eodag/resources/providers.yml, eodag/utils/__init__.py, tests/context.py, tests/units/test_download_plugins.py, tests/units/test_utils.py
- Refactors and updates `get_bucket_name_and_prefix()`
- updates `mundi` configuration with `bucket_path_level = 0` and up-to-date search endpoint
fixes #519
=> fix: aws bucket extraction

eodag/rest/utils.py, tests/units/test_stac_utils.py
Adds a `stac_formatted` parameter to `eodag.rest.utils.search_products()` to accept parameters that are not STAC formatted.
Needed by https://github.com/CS-SI/eodag-labextension/issues/71
=> fix: rest search without stac formatting

docs/_static/custom.css
fixes #466 css glitch in documentation parameters tables
=> docs: fixes params tables glitch

eodag/resources/product_types.yml
Fixes some `sensorType` fields in `product_types.yml` in order to align to [OpenSearch Extension for EO ](http://docs.opengeospatial.org/is/13-026r9/13-026r9.html) recommendations:
> sensorType: A string identifying the sensor type. Suggested   values are: OPTICAL, RADAR, ALTIMETRIC, ATMOSPHERIC, LIMB
=> fix: align sensorType to opensearch-eo

eodag/cli.py, eodag/rest/server.py, eodag/rest/utils.py, setup.cfg, tests/units/test_http_server.py
Do not run [flasgger](https://github.com/flasgger/flasgger) automatically, in order to be able to edit its configuration, which needs to be done before it is linked to the `Flask` app.
Needed by https://github.com/CS-SI/eodag-labextension/issues/81
Deprecated no more used functions: `rest.utils.format_product_types()`, `rest.utils.get_home_page_content()`, `rest.utils.get_templates_path()`.
Removed dependency to no more used `markdown`.
=> feat: do not run flasgger automatically

.pre-commit-config.yaml
Updates versions of pre-commit repos versions.
Fixes issue with `flake8` on `python3.7` raising:
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repo2rulx4j3/py_env-python3.7/bin/flake8", line 8, in <module>
sys.exit(main())
File "/home/runner/.cache/pre-commit/repo2rulx4j3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
app.run(argv)
File "/home/runner/.cache/pre-commit/repo2rulx4j3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
self._run(argv)
File "/home/runner/.cache/pre-commit/repo2rulx4j3/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line …
```
=> ci: pre-commit repos update

setup.cfg
Use `pytest-html < 3.2.0` until https://github.com/pytest-dev/pytest-html/issues/559 is fixed.
Fixes issue with `pytest-html 3.2.0` on windows:
```
Traceback (most recent call last):
File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "D:\a\eodag\eodag\.tox\py37\Scripts\pytest.EXE\__main__.py", line 7, in <module>
sys.exit(console_main())
File "D:\a\eodag\eodag\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 190, in console_main
code = main()
File "D:\a\eodag\eodag\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 168, in main
config=config
File …
```
=> fix: temporarily set pytest-html max version

eodag/plugins/download/http.py, tests/units/test_download_plugins.py
Only HEAD method was used to try extracting `filename` from `content-disposition` header.
Now also try GET method to get this header when download starts.
Also strips out filename from query args when it is obtained from parsed url.
=> fix: new methods to get assets filename from header

eodag/api/core.py
fixes rtype for [guess_product_type()](https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.guess_product_type)
=> docs: fixed rtype for guess_product_type

tests/units/test_core.py
Test for `eodag/api/core.py` goes from `(missing 66/531, coverage=88%)` to `(missing 44/531, coverage=92%)`
=> test: improve core test coverage

CHANGES.rst
post release typo fix in changelog
=> docs: changelog typo

eodag/api/core.py, eodag/plugins/authentication/keycloak.py, tests/integration/test_core_config.py
- Fixes some keycloak auth errors catching
- Log a warning instead of raising an exception if auth fails when discovering product types
=> fix: warning if keycloak auth error while discovering product types

.github/workflows/test.yml
Use `continue-on-error: true` option to skip error when running `Publish Unit Test Results` GH actions step:
```
Pull down action image 'ghcr.io/enricomi/publish-unit-test-result-action:v1.40'
/usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.40
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
Warning: Docker pull failed with exit code 1, back off 8.516 seconds before retry.
/usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.40
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
Warning: Docker pull failed with exit code 1, back off 9.323 seconds before retry.
/usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.40
Error response from daemon: received …
```
=> fix: continue if error on gh actions tests publish

eodag/api/core.py, tests/units/test_core.py
When calling `dag.list_product_types(provider="some_provider")` or `dag.fetch_product_types_list(provider="some_provider")` , only request this single provider
=> fix: fetch only given provider if specified

eodag/api/core.py, tests/units/test_core.py
Use [Product types discovery](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/2_providers_products_available.html#Product-types-discovery) before performing search on an unknown product type, in order to update `EODataAccessGateway` providers configuration.
=> feat: fetch ext product types before searching unkown product type

eodag/utils/stac_reader.py
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
Resolves #519 failure:
```
with open(url) as f:
OSError: [Errno 22] Invalid argument: 'https://capella-open-data.s3.us-west-2.amazonaws.com/stac/capella-open-data-by-datetime/capella-open-data-2021/capella-open-data-2021-4/capella-open-data-2021-4-10/CAPELLA_C03_SP_SLC_HH_20210410140302_20210410140304/CAPELLA_C03_SP_SLC_HH_20210410140302_20210410140304.json'
```
It was trying to read a remote json with the `read_local_json` (in `stac_reader`). As expected it failed, but (I think) with an unhandled exeception: an `OSError`, instead of a `FileNotFoundError`.
This behavior breaks the function, which is supposed to work or return a STACOpenerError.
=> Update read_local_json to catch OSErrors (#519)

eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/utils/__init__.py, tests/context.py, tests/units/test_utils.py
fixes #573 
Before this fix, some files could be deleted after download, during the product directory structure modification
=> fix: fixed flatten top dirs mechanism

setup.cfg
fixes issue when building docs:
```
WARNING: Pygments lexer name 'ipython3' is not known
```
The warnings where raised by `nbsphinx`.
Temporarily pin `ipython` until https://github.com/spatialaudio/nbsphinx/issues/687 is fixed
=> fix: pin ipython version in docs for nbsphinx

.github/workflows/test.yml, CONTRIBUTING.rst, setup.cfg, tox.ini
Adds support for `python3.11` and use it in github actions instead of `python3.10`.
Fixes #537
=> feat: add support for py311

eodag/plugins/search/qssearch.py
Fixes #571
Removes `product_type` from `kwargs` in `QueryStringSearch.query()` to prevent conflicts with other `QueryStringSearch` methods. 
This means that `product_type` cannot be used as custom search argument (it will be ignored with `QueryStringSearch` plugin).
=> fix: remove product_type custom arg from QueryStringSearch.query

eodag/plugins/search/static_stac_search.py
Fixes #570 
Disable `discover_product_types()` for `StaticStacSearch` plugin
=> fix: disable discover_product_types for StaticStacSearch

tox.ini
Fixes issue in windows tests / github actions:
```
INTERNALERROR> NotADirectoryError: [WinError 267] The directory name is invalid: 'test-reports/coverage--cov-report=xml:test-reports'
```
=> fix: missing space needed in pytest cli call

eodag/plugins/search/qssearch.py, tests/units/test_search_plugins.py
following #592, sort keywords for discovered product types to prevent unneeded PRs from github-actions bot
=> fix: ordered keywords in discovered product types

eodag/resources/providers.yml, tests/test_end_to_end.py, tests/units/test_apis_plugins.py, tests/units/test_core.py
`L8_OLI_TIRS_C1L1` removed from `usgs` available product types, following https://www.usgs.gov/landsat-missions/news/landsat-collection-1-datasets-be-removed-december-30-2022:
> All Landsat Collection 1 data and science products in the USGS archives will become unavailable on December 30, 2022. Additionally, the ability to submit orders through the ESPA On-Demand Interface for Landsat Collection 1-based science products will end on Friday, December 16, 2022.
=> fix: landsat c1 no more available on usgs

eodag/plugins/download/aws.py, tests/units/test_download_plugins.py, tests/units/test_safe_build.py
- renamed `AwsDownload.get_bucket_name_and_prefix()` to `AwsDownload.get_product_bucket_name_and_prefix()`
- asset out of SAFE pattern won't break `AwsDownload.download()`
- more `AwsDownload` tests
=> fix: AwsDownload SAFE build fix and more tests

eodag/plugins/apis/usgs.py, tests/test_end_to_end.py
In `usgs` API plugin, use available `downloadSystem` from `download_options`.
Fixes #581
=> fix: check usgs available downloadSystem in download_options

eodag/api/product/metadata_mapping.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, tests/units/test_search_plugins.py
`metadata_pre_mapping` as new entry in `ODataV4Search` configuration.
Enables a 2 step  `normalize_results()` with a pre-mapping that simplifies metadata parsing performed in the 2nd step.
For example, goes from `$.Metadata[?(@.id="foo")].value` to `$.Metadata.foo.value`
=> feat: simplify odata metadata mapping using pre-mapping

eodag/plugins/download/base.py, tests/units/test_download_plugins.py
Improve [download() wait time](https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/7_download.html#Order-OFFLINE-products) precision to microsecond
=> fix: better download wait time precision

eodag/plugins/search/qssearch.py
Fixes free text search operands filtering in `format_free_text_search()` usage from `ODataV4Search` plugin.
=> fix: odata free text search operands filter

eodag/api/core.py, eodag/api/product/metadata_mapping.py, eodag/plugins/apis/usgs.py, eodag/plugins/search/base.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, eodag/resources/stac_provider.yml
Fixes #520 , optimizes `jsonpath.parse()` using new `common_metadata_mapping_path` entry in providers configuration.
The time saving is noticeable, see the following chart comparing search times for a random search with and without optimization:
=> fix: optimized jsonpath.parse using common_metadata_mapping_path

eodag/plugins/search/qssearch.py, tests/test_end_to_end.py
Remove `peps` specific code from `QueryStringSearch` for `S2_MSI_L1C` usage, that handled 2 collections `S2` and `S2ST`.
Related to https://peps-mission.cnes.fr/fr/peps-info-suppression-des-donnees-sentinel-2-datatake
=> fix: simplify S2_MSI_L1C internal usage with peps

eodag/api/core.py, eodag/rest/utils.py, pytest.ini, setup.cfg, tests/__init__.py, tests/context.py, tests/integration/test_core_config.py, tests/integration/test_search_stac_static.py, tests/test_end_to_end.py, tests/units/test_apis_plugins.py, tests/units/test_core.py, tests/units/test_eoproduct.py, tests/units/test_http_server.py, tests/units/test_safe_build.py, tests/units/test_stac_utils.py, tox.ini
Tests fixes and optimizing:
- check networks calls with [pytest-socket](https://github.com/miketheman/pytest-socket)
- all doctests except the one from `eodag/utils` moved to `tests` folder to better handle environment for these tests
- [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) and [pytest-instafail](https://github.com/pytest-dev/pytest-instafail) usage
- some other fixes
Local tests duration example for a single environment:
- before: 152s
- after: 46s
=> test: optimizes and fixes tests

eodag/utils/__init__.py, tests/units/test_download_plugins.py, tests/units/test_utils.py
Fixes #633 
Prevents error raised when trying to use `flatten_top_directories()` on a directory containing a single file or when downloading a product having a single asset with download plugin configured with `flatten_top_dirs: true`.
=> fix: flatten_top_directories on single file

eodag/plugins/download/base.py
Fixes issue in the warning message following a download timeout (that could be caused by a network issue):
```
File /path/to/lib/python3.9/site-packages/eodag/plugins/download/base.py:517, in Download.download_all(self, products, auth, downloaded_callback, progress_callback, wait, timeout, **kwargs)
513 sleep(wait_seconds + 1)
514 elif len(products) > 0 and datetime.now() >= stop_time:
515 logger.warning(
516 f"{len(products)} products could not be downloaded:"
--> 517 f"{' ' + [prod.properties['title'] for prod in products]}",
518 )
TypeError: can only concatenate str (not "list") to str
```
=> fix: not-downloaded products warning

eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, tests/units/test_search_plugins.py
Related to #389 
- Fixes cloud cover disabled for radar product types
- Fixes `onda` queryable paramaters configuration
=> fix: cloud cover disabled for radar product types and onda queryable params

docs/getting_started_guide/configure.rst
Fixes #618 
Added a note with templates for setting the credentials environment variables for both providers using the authentication plugin and the API plugin.
=> docs: credentials setting using environment variables better doc

eodag/resources/providers.yml
Changes creodias `max_items_per_page` search setting from 2000 to 1000, which caused issues when using `search_all()` method.
=> fix: creodias max_items_per_page

eodag/plugins/search/qssearch.py, eodag/utils/__init__.py
Prevents duplicated `free_text_search_operations` entries in `ODataV4Search` configuration when searching several times using a custom (not already configured) query parameter
=> fix: prevent duplicated ODataV4Search custom args

eodag/api/product/_product.py, tests/units/test_eoproduct.py
Better handle missing geometry when building [EOProduct](https://eodag.readthedocs.io/en/stable/api_reference/eoproduct.html#eodag.api.product._product.EOProduct):
- raises `MisconfiguredError` with explicit message on missing geometry and no `defaultGeometry` configured
- uses `properties["defaultGeometry"]` as default geometry if exists
=> feat: EOProduct defaultGeometry property

eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, tests/units/test_metadata_mapping.py
- Adds a new method `convert_from_georss()` in `metadata_mapping`
- Handle `mundi` GeoRSS geometries
- `-180 -90 180 90` as `defaultGeometry` for `mundi` products without geometry
=> feat: mundi georss geometry handling

eodag/api/product/_product.py, eodag/config.py, eodag/plugins/apis/usgs.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/qsauth.py, eodag/plugins/authentication/token.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/search/qssearch.py, eodag/utils/__init__.py, tests/context.py, tests/integration/test_core_config.py, tests/test_config.py, tests/units/test_apis_plugins.py, tests/units/test_auth_plugins.py, tests/units/test_download_plugins.py, tests/units/test_eoproduct.py, tests/units/test_search_plugins.py
fixes #614
Requests headers are now customized as follows: `{"User-Agent": <EODAG_VERSION>}`
=> feat: customize requests headers with EODAG version as user agent

eodag/api/core.py, eodag/plugins/apis/usgs.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/qssearch.py, tests/integration/test_core_search_errors.py, tests/resources/wrong_credentials_conf.yml, tests/test_end_to_end.py
Fixes [search](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/4_search.html#Search-methods) error handling, broken since `v2.9.0` and #632, and adds associated tests
=> fix: search errors handling

setup.cfg
Pin `sphinx-book-theme` version to the latest stable before `v1.0.0`. 
`v1.0.0` was just released and theme settings need to be adapted: https://sphinx-book-theme.readthedocs.io/en/latest/changelog.html#v1-0-0-2023-03-01
=> docs: pin sphinx-book-theme version

tests/units/test_eoproduct.py
Adds an explicit error message to help understanding randomly failing `test_eoproduct_register_downloader_resolve_ignored`
=> test: explicit error message for test_eoproduct_register_downloader_resolve_ignored

eodag/api/core.py, eodag/api/product/metadata_mapping.py, eodag/config.py, eodag/plugins/apis/usgs.py, eodag/rest/stac.py, eodag/utils/__init__.py, tests/context.py, tests/units/test_core.py, tests/units/test_utils.py
Customized and faster deepcopy inspired by https://stackoverflow.com/a/45858907
```py
import copy
import timeit
from eodag.config import load_stac_config
from eodag.utils import deepcopy
stac_config = load_stac_config()
print("New deepcopy: %s ms" % timeit.timeit("deepcopy(stac_config)", globals=locals(), number=1000))
print("copy.deepcopy: %s ms" % timeit.timeit("copy.deepcopy(stac_config)", globals=locals(), number=1000))
```
Results in:
```
New deepcopy: 0.21507359799943515 ms
copy.deepcopy: 7.414625944002182 ms
```
=> feat: customized and faster deepcopy

eodag/api/product/metadata_mapping.py, setup.cfg, tests/units/test_download_plugins.py, tests/units/test_metadata_mapping.py
Fixes inverted x/y when using `shapely.ops.transform()` in `convert_from_ewkt()` and `convert_from_georss()`, and supresses deprecation warning following https://shapely.readthedocs.io/en/latest/manual.html#other-transformations guidelines
=> fix: shapely transform inverted xy and warning

eodag/api/core.py, eodag/api/product/metadata_mapping.py, eodag/plugins/apis/usgs.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/search/base.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, eodag/rest/utils.py, eodag/utils/__init__.py, tests/context.py, tests/test_config.py, tests/units/test_core.py, tests/units/test_http_server.py, tests/units/test_search_plugins.py, tests/units/test_stac_utils.py
Refactors metadata-mapping to perform `jsonpath` build/parse during search plugins init step.
Related to #628
Also changes environment variables mocking during tests.
=> refactor: metadata parsing

.github/workflows/deploy.yml, .github/workflows/fetch.yml, .github/workflows/test.yml
Upgrades github actions to prevent some remaining warnings:
- https://github.com/actions/setup-python `@v4`
- https://github.com/EnricoMi/publish-unit-test-result-action `@v2`
=> ci: upgrade gh-actions

eodag/plugins/apis/cds.py, eodag/plugins/search/qssearch.py, eodag/rest/stac.py, tests/context.py, tests/units/test_apis_plugins.py
Default dates usage with [CdsApi](https://eodag.readthedocs.io/en/latest/plugins_reference/generated/eodag.plugins.apis.cds.CdsApi.html) (`cop_ads` and `cop_cds` providers).
Refactored `CdsApi` plugin using `BuildPostSearchResult` plugin.
=> fix: CdsApi default dates and refactor

tests/units/test_apis_plugins.py
Updates `CdsApi` tests following [cdsapi v0.6.0 update](https://github.com/ecmwf/cdsapi/releases/tag/0.6.0 )
=> test: fix CdsApi test following provider api update

eodag/api/core.py, eodag/config.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, eodag/resources/stac_provider.yml, eodag/utils/__init__.py, eodag/utils/stac_reader.py, setup.cfg, tests/units/test_core.py, tests/units/test_search_plugins.py
[fetch_product_types_list()](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/2_providers_products_available.html#Product-types-discovery) optimization, including:
- `orjson` usage
- `jsonpath.parse()` optimized for nested lists
- `product_types.abstract` type changed in `whoosh` index
- cached `load_config()`
With `planetary_computer` external product types included, `fetch_product_types_list()` goes from 3.04s to 0.49s
=> feat: fetch product types optimization

eodag/api/core.py, tests/units/test_core.py
`guess_product_type()` should return given `productType` if specified
=> fix: guess_product_type should return given productType if specified

eodag/resources/stac.yml
Updates STAC API version to [v1.0.0-rc.3](https://github.com/radiantearth/stac-api-spec/releases/tag/v1.0.0-rc.3)
=> refactor: STAC API 1.0.0-beta.3 to 1.0.0-rc.3

eodag/rest/stac.py
Fixes missing `sensorType` error when serving STAC items obtaining when searching for discovered product types
=> fix: STAC search items for discovered product types

docker/run-stac-server.sh
Fixes `eodag-server` dockerfile to have running process with pid 1 and accept SIGTERM signal
=> fix: eodag-server docker sigterm

docker/stac-browser.dockerfile
Updates STAC browser catalog url parameter name from `CATALOG_URL` to `catalogUrl`. See https://github.com/radiantearth/stac-browser#migrate-from-old-versions
=> fix: update STAC browser catalogUrl param name

eodag/rest/stac.py
fixes cloud-cover filtering through dynamically built STAC server catalogs (i.e. http://127.0.0.1:5000/S2_MSI_L1C/cloud_cover/10/items)
=> fix: stac server catalogs cloud-cover filtering

eodag/rest/utils.py
fixes dates filtering through dynamically built STAC server catalogs mixed with query arguments (i.e. http://127.0.0.1:5000/S2_MSI_L1C/year/2019/items?datetime=2018-12-01/2019-01-31)
=> fix: stac server catalogs dates filtering

README.rst, docs/stac_rest.rst
Adds links to `eodag-server`, [eodag STAC API server](https://eodag.readthedocs.io/en/latest/stac_rest.html) docker image on https://hub.docker.com/r/csspace/eodag-server
=> docs: ref to dockerhub eodag-server

.github/workflows/test.yml, setup.cfg
- Remove `tests` folder from code coverage.
- Distinct ubuntu and windows tests results reports for each python version in PR comments (github actions)
- Distinct ubuntu and windows tests coverage reports in PR comments (github actions)
=> ci: remove tests from coverage

setup.cfg
Set flask `2.2.X` as max version, because of incompatibility with `flasgger`.
See https://github.com/flasgger/flasgger/issues/562
=> fix: flask 2.2.x as max version

.github/workflows/test.yml, setup.cfg, tox.ini
Code coverage reports for Windows and Ubuntu post in distinct PR comments to avoid duplicate lines bug with github action.
Related to https://github.com/5monkeys/cobertura-action/issues/68
=> ci: coverage to distinct pr comments

eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml
`mundi` opensearch API sometimes omit to return `storageStatus`. In this case, this means that the product is `OFFLINE`: set this value in the metadata. This will also trigger product order when launching download.
Related to #645
=> fix: handle mundi missing storageStatus

eodag/rest/server.py, eodag/rest/utils.py, tests/units/test_http_server.py
The changes in this pull request solve the problem that only one request can be handled at the same time which could lead to long queues. Now, several different requests can be handled at the same time, e.g. a search can be done during a download.
Related to #701
=> feat: server-mode parallel requests

eodag/plugins/download/http.py, tests/units/test_download_plugins.py
Sanitizes downloaded assets paths, and fixes issue when downloading a `hydroweb_next` product on windows:
```py
from eodag import EODataAccessGateway
dag = EODataAccessGateway()
search_results = dag.search_all(
productType="SWOT_L2_HR_LAKESP_PRIOR_SAMPLE_V1_2",
)
downloaded_paths = dag.download_all(search_results)
```
```
URN:FEATURE:DATA:hysope2:2630a915-c732-3730-be8b-d21ef954d411:V1:   0%|          | 0.00/3.35M [00:00<?, ?B/s][A2023-05-25 17:05:45,145 eodag.plugins.download.base      [WARNING ] (base             ) A problem occurred during download of product: EOProduct(id=URN:FEATURE:DATA:hysope2:2630a915-c732-3730-be8b-d21ef954d411:V1, provider=hydroweb_next). Skipping it
2023-05-25 17:05:45,147 eodag.plugins.download.base      [DEBUG   ] (base             )
Traceback (most recent …
```
=> fix: sanitize downloaded assets paths

eodag/rest/utils.py, tests/units/test_http_server.py
Fixes #733
In server mode, products download with python external api providers works once again by removing the set up of `extract` attribute of the plugin `download` because this plugin is not theirs by their nature. 
It does not have an impact on extraction process because `extraction` is directly set in `download` method call parameters and it takes priority on providers configuration.
=> fix: server-mode download for ext api providers

eodag/resources/providers.yml, tests/units/test_apis_plugins.py
Fixes #747 
Products `CAMS_EAC4` download works once again by removing the parameter `step` in its configuration for `cop_ads`.
=> fix: remove `step` parameter in CAMS_EAC4 configuration

docs/getting_started_guide/configure.rst, docs/getting_started_guide/register.rst, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/resources/providers.yml, eodag/resources/user_conf_template.yml, tests/test_end_to_end.py, tests/units/test_auth_plugins.py
Fixes #752
Updates `creodias` configuration to use its new [Two-Factor authentication mechanism](https://creodias.docs.cloudferro.com/en/latest/gettingstarted/Two-Factor-Authentication-for-Creodias-Site.html), using a *One Time Password*.
Documentation updated with:
- [provider registration for creodias](https://eodag--763.org.readthedocs.build/en/763/getting_started_guide/register.html)
- [Authenticate using an OTP / One Time Password (Two-Factor authentication)](https://eodag--763.org.readthedocs.build/en/763/getting_started_guide/configure.html#authenticate-using-an-otp-one-time-password-two-factor-authentication)
=> fix: update creodias auth to Creodias-new

docker/stac-server.dockerfile
Fixes #761
In STAC server dockerfile, create home directory when adding user
=> fix: docker user home dir

eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, tests/units/test_download_plugins.py
Fixes #728 
While downloading a product with a STAC provider, we use the `downloadLink` property if exists instead of downloading every asset.
The `ignore_assets` attribute had already been implemented for AWS download plugin, now it is also operational for HTTP download plugin so every STAC provider can use it.
=> feat: use `downloadLink` if exists for STAC providers

docs/api_reference/core.rst, docs/cli_user_guide.rst, docs/getting_started_guide/configure.rst, docs/getting_started_guide/register.rst, docs/notebooks/api_user_guide/4_search.ipynb
Fixes #315 
- gives more examples for the use of guess_product_type
- explains the use of whoosh query language
- adds documentation for using search with product type guessing in the cli
Also fixes #719 and #732: typos, dead links, and minor updates
=> docs: extend documentation for guess_product_type and other minor updates

eodag/plugins/authentication/keycloak.py
Add an additional error log in `KeycloakOIDCPasswordAuth` plugin error handling.
Related to #770
=> fix: more verbose keycloak auth plugin errors

eodag/rest/stac.py, tests/units/test_http_server.py
Fixes #748 
In server mode, add provider as downloadlink query-arg in assets if specified in search
=> fix: missing provider in stac downloadLink

readthedocs.yml
Fixes issues when building readthedocs image: RTD performs a shallow git fetch with the last 50 commits, which prevented `setuptools_scm` to get `eodag` version and breaked its installation.
It is now configured to perform an unshallow git fetch
=> fix: readthedocs git fetch unshallow

setup.cfg
Fixes `request-ftp` requirement breaking pypi package build
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
Invalid value for requires_dist. Error: Can't have direct dependency:  
'requests-ftp @                                                        
https://github.com/Lukasa/requests-ftp/archive/refs/heads/master.zip'  
```
=> fix: request-ftp requirement

eodag/api/core.py, eodag/plugins/download/http.py, tests/context.py, tests/integration/test_core_search_results.py
Fixes download issues caused by missing authentication object in search results following #753
=> fix: missing auth in search results

eodag/plugins/authentication/token.py, tests/units/test_auth_plugins.py, tests/units/test_search_plugins.py
- retries are added to the request to fetch the token in case certain errors occur (mainly intended for random unauthorized errors from wekeo)
- the token is now correctly updated in the authorization header when the previous token is expired and a new token is returned by the provider
=> fix: forbidden and unauthorized errors in token auth

eodag/rest/server.py, tests/units/test_http_server.py
Send 500 http "Internal server error" to the client when capturing server side `AuthenticationError`
=> fix: 500 http error for server internal auth errors

eodag/rest/server.py, eodag/rest/utils.py, tests/units/test_http_server.py
This MR implements the `/queryables` and `/collections/{collection_id}/queryables` endpoints as per the [STAC API documentation ](https://github.com/radiantearth/stac-api-spec/blob/master/fragments/filter/README.md#queryables).
Fixes #792
=> feat(server): add queryables endpoints

eodag/rest/server.py, eodag/rest/utils.py, tests/units/test_http_server.py
Fixes server mode missing `intersects` parameter in pydantic request model. This caused lacking geometry filtering using this parameter
=> fix(server): missing intersects parameter in request body model

eodag/rest/utils.py, tests/units/test_stac_utils.py
Fixes #784 
In server mode, remove deprecated support for geom and box filters
=> fix(server): use only one of bbox and intersects on search

eodag/api/core.py, eodag/plugins/manager.py, tests/units/test_core.py
Authenticate against the provider directly during the `_do_search` method. The `_prepare_search` has been refactored to not include anything related to authentication.
Fix #801
=> fix: authenticate only when performing search

eodag/resources/providers.yml
Simplifies mundi authentication mechanism using `HTTPHeaderAuth`.
Fixes #736
=> fix: simplified mundi auth using HTTPHeaderAuth

eodag/api/core.py, eodag/rest/utils.py
Fixes provider handling issue when searching products by id, following https://github.com/CS-SI/eodag/pull/790
=> fix: bad providers handling when searching by id

eodag/rest/utils.py, tests/units/test_http_server.py
Prevents preferred provider to be passed as `search()` argument in server mode, which would prevent provider switch and fallback mechanism.
Related to #753 and #807
=> fix(server): provider setting in server mode

eodag/rest/utils.py, tests/units/test_http_server.py
Do not use `raise_errors=True` in server mode search to enable search fallback mechanism
=> fix(server): raise_errors disabled for server search fallback

eodag/rest/server.py, tests/units/test_http_server.py
Update server body model to search by ids (missing `ids` parameter)
Related to #776
=> fix: update server body model to search by ids

setup.cfg
Temporary limit `jsonpath-ng` under latest 1.6.0 until tests are fixed
=> fix: limit jsonpath-ng version

eodag/resources/providers.yml
datahub URL redirects to zipper url.
Use CREODIAS zipper URL instead of datahub for downloadLink to avoid the redirect.
=> perf(creodias): use zipper URL to avoid unecessary redirect

eodag/resources/stac.yml, eodag/rest/server.py, eodag/rest/stac.py, tests/units/test_http_server.py
Correct the links in the STAC model. It fix the links on the following endpoints:
- /collections
- /collections/{collection_id}
- /collections/{collection_id}/items
- /collections/{collection_id}/items/{item_id}
=> fix(server): correct links in stac model

eodag/rest/utils.py
Better handle "intersects" geometry conversion error from json to dict then to shapely geometry
=> fix(server): load json string intersects param as dict

docs/getting_started_guide/configure.rst, eodag/config.py, tests/resources/file_providers_override.yml, tests/units/test_core.py
Fixes #799 
`EODAG_PROVIDERS_CFG_FILE` environment variable usage to set a custom `providers.yml` file path
=> feat: EODAG_PROVIDERS_CFG_FILE env var

eodag/api/core.py, eodag/api/product/_product.py, eodag/config.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/qsauth.py, eodag/plugins/authentication/sas_auth.py, eodag/plugins/authentication/token.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/plugins/search/static_stac_search.py, eodag/resources/providers.yml, eodag/utils/__init__.py, eodag/utils/stac_reader.py, tests/context.py, tests/integration/test_download_auth.py, tests/units/test_download_plugins.py, tests/units/test_search_plugins.py, utils/params_mapping_to_csv.py
- Adds a default `timeout` (60s for `creodias`, `onda`, `wekeo`) in provider search configuration for search requests
- Adds some missing requests timeouts and user-agent
- Moves `HTTP_REQ_TIMEOUT` and `DEFAULT_STREAM_REQUESTS_TIMEOUT` to `eodag.utils`
- Less verbosity in `INFO` level for `DataRequestSearch` logging
=> feat: per provider search timetout

eodag/rest/server.py, eodag/utils/logging.py
- thread id now appears in DEBUG logging level (`setup_logging(3)`)
- in server mode, log all requests urls and bodies
Fixes #815
=> feat: thread id and server requests in debug logs

eodag/rest/server.py
Improves #741 
Enables multi-threading for all requests in server mode
=> fix(server): multithreaded requests

eodag/api/core.py, eodag/api/product/metadata_mapping.py, tests/integration/test_core_config.py
The pruned providers are saved in `EODataAccessGateway._pruned_providers_config` and restored when the configuration is updated.
=> feat: restore pruned providers when configuration is updated

docs/conf.py, eodag/plugins/authentication/keycloak.py, eodag/rest/server.py, eodag/utils/notebook.py, pyproject.toml, setup.cfg
This PR addresses #387 and adds basic type information for eodag.
Usage of eodag has been tested in a `mypy`-enabled environment and does no longer result in a warning about missing type information.
=> feat: add static type information

eodag/resources/providers.yml
Fixes #845 
- EWKT geometries extraction for `creodias` and `cop_dataspace` (thanks @gasparakos)
- add greater search timeout (60s) on `cop_dataspace`
=> fix: ewkt extraction for creodias and cop_dataspace

eodag/resources/stac.yml, eodag/rest/stac.py, eodag/rest/utils.py, tests/units/test_stac_utils.py
In server mode all available providers of a collection sorted by priority are no returned at the collections endpoint (GET /collections, GET /collections/id)
=> feat: return all available providers for collection

tests/test_end_to_end.py
Updates end-to-end test `test_end_to_end_complete_peps()` that could not be executed with current configuration
=> test: update test_end_to_end_complete_peps

eodag/plugins/search/data_request_search.py
Return the single requested item if the requested item id is found in the results.
=> fix: return only user requested DataRequestSearch item if id is present

eodag/api/product/_product.py, eodag/api/product/metadata_mapping.py, eodag/plugins/apis/base.py, eodag/plugins/apis/cds.py, eodag/plugins/apis/ecmwf.py, eodag/plugins/apis/usgs.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/sas_auth.py, eodag/plugins/crunch/filter_date.py, eodag/plugins/crunch/filter_latest_intersect.py, eodag/plugins/crunch/filter_latest_tpl_name.py, eodag/plugins/crunch/filter_overlap.py, eodag/plugins/crunch/filter_property.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/manager.py, eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/csw.py, eodag/plugins/search/qssearch.py, eodag/plugins/search/static_stac_search.py, eodag/utils/logging.py, tests/units/test_download_plugins.py, tests/units/test_eoproduct.py, tests/units/test_safe_build.py, tests/units/test_search_plugins.py
Fixes #876
- removes duplicate `module` information from `logging` (also in logger name)
- shorten loggers names: remove `plugins`, `api`, `filter_`
=> fix: remove module from logging and shorten loggers names

eodag/resources/providers.yml
Set `creodias` search timeout to 20s. Needed for _search-by-id_ that can last for more than 10s on this provider
=> fix: set creodias search timeout to 20s

setup.cfg
Set `responses` max version to less than `0.24.0`, to prevent conflicts with `pytest-socket`.
See https://github.com/getsentry/responses/issues/691
=> fix: set responses max version lt 0.24.0

.github/workflows/deploy.yml, .github/workflows/fetch.yml, .github/workflows/test.yml, CONTRIBUTING.rst, eodag/utils/__init__.py, setup.cfg, tox.ini
=> feat: removed Python 3.7 support

.github/workflows/test.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, setup.cfg, tox.ini
Update python max version to 3.12
> `tox -e docs` fails cause the wheel for netCDF4 is not available for Python 3.12 yet.
> See https://github.com/Unidata/netcdf4-python/issues/1282
edit: can be merged now that netCDF4 is available for py312
=> feat: Python 3.12 update

eodag/resources/providers.yml
use the wkt format for the geometry and defaultGeometry parameters in providers.yml
=> refactor: use wkt format for geometry in providers config

eodag/api/core.py, eodag/plugins/manager.py
Adds a new method `PluginManager.rebuild()` to avoid creating a new manager when only rebuild is needed, and prevent issues with providers settings and priorities.
Fixes #567
=> fix: plugin manager rebuild

docs/notebooks/api_user_guide/5_serialize_deserialize.ipynb
Corrected typo in the "Serialize/Deserialize" page of the documentation.
Fixes #900
=> docs: deserialize documentation typo

tests/test_end_to_end.py
Updates `test_search_by_tile` following `creodias` and `cop_dataspace` API updates.
Related to #866 and #883
=> test: update test_search_by_tile

eodag/resources/stac_api.yml, eodag/rest/server.py
This PR updates the openAPI static file located at `./eodag/resources/stac_api.yml`, updating the description and summaries of endpoints as well as adding a `query` entry in the list of parameters.
It fixes the issue #839
=> docs: update open api static spec

eodag/plugins/authentication/keycloak.py, tests/units/test_auth_plugins.py
For keycloak authentication it is now checked if the access token is still valid before a new token request is done. If available, the refresh token is used to request a new access token.
=> fix: use refresh token to get access token in keycloak auth

eodag/resources/providers.yml
Updates `creodias` and `cop_dataspace` configuration to return search result count.
Set search timeout to 60s for these providers, as a search without spatio-temporal filtering can last 30s
Related to #866 and #883
=> fix: creodias & cop_dataspace search result count

tests/test_cli.py, tests/units/test_apis_plugins.py, tests/units/test_core.py, tests/units/test_utils.py
reset logger after tests. Fixes logger-related issues in tests
=> test: reset logger after tests

docs/notebooks/api_user_guide/7_download.ipynb, eodag/api/product/_assets.py, eodag/api/product/_product.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/search/qssearch.py, eodag/rest/server.py, eodag/rest/stac.py, eodag/rest/utils.py, tests/units/test_download_plugins.py, tests/units/test_stac_utils.py
if a regex expression is passed in the parameter `asset` in the download only the assets matching this expression are downloaded (only working if the provider API returns individual assets and not a zip file); implemented for the `HTTPDownload` and `AwsDownload` plugins (s3rest plugin not used anymore after removal of mundi).
Client mode usage:
```py
path = dag.download(eo_product, asset=asset_key, **optional_download_kwargs)
path = eo_product.assets[asset_key].download(**optional_download_kwargs)
```
Server mode usage:
http://127.0.0.1:5000/path/to/some/item/download/asset_key
=> feat: download assets subset

docs/api_reference/core.rst, eodag/api/core.py, eodag/rest/server.py, eodag/rest/utils.py, tests/context.py, tests/units/test_core.py
Implements a new core method `def get_queryables(provider=None, product_type=None) -> List[str]`:
- If no `provider` and no `product_type` are passed, then returns default search method queryable parameters: `["productType", "start", "end", "geom", "locations", "id"]`
- If a `provider` is passed (but no `product_type`), then returns its queryable parameters from provider's config
- If a `product_type` is passed (but no `provider`), then return the intersection of the queryables of all the providers supporting it
- If both a `product_type` and a `provider` are passed, then returns the queryable parameters from provider's config and the queryable parameters for that product type
The following exceptions are raised:
- `UnsupportedProvider()` if the given `provider` is not found
- …
=> feat: implement new core method get_queryables

.gitignore, eodag/resources/stac.yml, eodag/rest/server.py, eodag/rest/stac.py, eodag/rest/utils.py, tests/units/test_stac_utils.py
This PR fixes the `next` link display in `search` requests (both `GET` and `POST`).
It provides a URL to the next page and the json body in the case of a `POST` request.
=> fix(server): properly display next page object

eodag/resources/providers.yml
Replaces `quicklook` empty property with `thumbnail` on `creodias` and `cop_dataspace`
=> fix: creodias and cop_dataspace quicklook

eodag/rest/stac.py, tests/units/test_stac_utils.py
Fixes #767 
Makes origin assets links available through `asset["alternate"]["origin"]["href"]` in server STAC response.
```json
{
"features": [
{
"id": "some-product",
"assets": {
"B01": {
"title": "Download link",
"href": "http://127.0.0.1:5000/collections/some-collection/items/some-product/download/B01",
"alternate": {
"origin": {
"title": "Origin asset link",
"href": "s3://path/to/B01-asset"
}
}
}
}
}
]
}
```
=> feat(server): stac alternate assets

tests/units/test_http_server.py
Fixes issues in github actions related to conflicting loaded environment variables
=> test: fix env var loading in test_http_server

docs/api_reference/core.rst, eodag/api/core.py, eodag/api/queryables.py, eodag/rest/server.py, eodag/rest/utils.py, eodag/utils/__init__.py, tests/resources/stac/queryables.json, tests/units/test_core.py, tests/units/test_http_server.py
- When the queryables are fetched for a specific provider, we try to call the queryables endpoint of the provider (currently only available for planetary_computer) to retrieve additional queryables from the provider.
- renamed `core.get_queryables()` to `core.list_queryables()`
- some queryables refactoring
=> feat: list provider-specific queryables

eodag/rest/server.py, tests/units/test_http_server.py
In server-mode, fixes returned common queryables for a given provider (http://127.0.0.1:5000/queryables?provider=peps)
=> fix(server): common queryables for given provider

eodag/plugins/search/qssearch.py, tests/units/test_search_plugins.py
Fixes issue when searching `S1_SAR_GRD` on `astraea_eod`, caused by a problem when parsing its product-type specific metadata-mapping:
```
KeyError: 'aswPath'
```
=> fix: astraea_eod product-type specific metadata-mapping

setup.cfg
Pin `sphinxcontrib-*` dependencies that make documentation build crash because they need `sphinx > 5`
=> build(docs): pin sphinxcontrib dependencies

eodag/api/core.py, eodag/config.py, eodag/plugins/apis/base.py, eodag/plugins/apis/usgs.py, eodag/plugins/download/http.py, eodag/plugins/search/base.py, eodag/plugins/search/qssearch.py, eodag/rest/types/stac_queryables.py, eodag/types/__init__.py, eodag/utils/__init__.py, tests/test_config.py
Fixes #985 and #973
- Cast loaded environment variables type using `PluginConfig` parameters type-hints.
- also adds some more type hint fixes
=> fix: cast loaded env vars type using config type-hints

eodag/api/core.py, eodag/rest/utils.py, eodag/utils/exceptions.py, tests/units/test_stac_utils.py
- raises an error in server mode if search fallback fails
- `raise_errors` enabled when search by id
=> fix(server): raise error if search fallback fails

eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/qsauth.py, eodag/plugins/authentication/sas_auth.py, eodag/plugins/authentication/token.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/rest/server.py, eodag/rest/utils.py, eodag/utils/exceptions.py, tests/units/test_http_server.py, tests/units/test_search_plugins.py
handle timeout error in server mode
=> feat: add timeout error

tests/test_cli.py
Test product-types from all providers instead of just for a random one in `test_eodag_list_product_type_with_provider_ok`
=> test: all product_types list instead of random

eodag/api/core.py, eodag/plugins/apis/base.py, eodag/plugins/search/base.py, eodag/plugins/search/qssearch.py, eodag/rest/types/stac_queryables.py, eodag/types/__init__.py, tests/context.py, tests/units/test_core.py
Following https://github.com/CS-SI/eodag/pull/974 (no release between these 2 Pull Requests), 
changes `list_queryables()` output from 
`Dict[str, Tuple[Annotated[Any, FieldInfo], Any]]`
to
`Dict[str, Annotated[Any, FieldInfo]]`.
Previous format returned *field default value* in the the 2nd argument of the tuple.
This is not needed any more as this value can be included in `FieldInfo`.
Also, `pydantic.create_model` can be still be used with `list_queryables()` output:
- before:
```py
>>> from pydantic import create_model
>>> from eodag import EODataAccessGateway
>>> dag = EODataAccessGateway()
>>> queryables = dag.list_queryables(product_type="S2_MSI_L1C", provider="peps")
>>> queryables
{'productType': (typing.Annotated[str, FieldInfo(annotation=NoneType, required=True)], None), ...}
>>> …
```
=> refactor: queryables type to Annotated

README.rst, eodag/api/core.py
This PR simply adds an unindexed field to the product types Schema, not used inside of EODAG but relevant for sharing configuration.
=> refactor(config/productTypes): ignore unindexed fields

eodag/api/product/_assets.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/search/creodias_s3.py
implements direct streaming of assets for aws download plugin
=> Stream download aws

docs/cli_user_guide.rst, eodag/cli.py
fixes #963
Following https://github.com/CS-SI/eodag-cube/pull/43, removes limited rpc server
=> fix: remove rpc server

docs/_static/params_mapping_extra.csv, eodag/resources/providers.yml
Add missing `tileIdentifier` queryable  for `creodias`, `creodias_s3` and `cop_dataspace`
=> fix: missing tileIdentifier for creodias and cop_dataspace

setup.cfg
Following #469 and now that `pyproj` was removed from `OWSLib` dependencies, remove `OWSLib` version upper limit
=> build: remove owslib version upper limit

docs/getting_started_guide/configure.rst
Adds a note in documentation to avoid quotes in settings stored in the YAML configuration file.
Related to #1015
=> docs: yaml settings quoting

.github/workflows/test.yml
Updates github actions coverage report in Pull Requests, using https://github.com/insightsengineering/coverage-action
=> ci: github actions coverage report update

eodag/plugins/apis/base.py, eodag/plugins/download/base.py, eodag/plugins/download/s3rest.py, tests/test_end_to_end.py
Fixes #994 
Avoid downloading the same product type from different providers.
The record hash is build from the concatenation of `product_type + "-" + id`
=> feat: generate record hash from product_type + id

eodag/plugins/download/http.py, tests/units/test_download_plugins.py
In `HTTPDownload` the assets are downloaded to a temporary file with suffix `~`. When the download is completed the file is renamed to remove the suffix. If the file was already correctly downloaded, the asset will not be downloaded again.
=> feat: resume interrupted assets download using HTTPDownload

eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, tests/units/test_metadata_mapping.py
Adds a new metadata-mapping convert method `convert_dict_filter()` to help filtering assets.
Method used to update providers configuration:
- `earth_search` only lists `s3` assets
- `earth_search_cog` only lists `http` assets
=> feat: configurable assets filtering

eodag/plugins/apis/base.py, tests/units/test_apis_plugins.py
Fixes #1047
Remove `metadata_mapping` from `CdsApi` queryables
=> fix: remove metadata_mapping from CdsApi queryables

eodag/api/core.py, eodag/api/product/_assets.py, eodag/api/product/_product.py, eodag/api/product/metadata_mapping.py, eodag/plugins/apis/base.py, eodag/plugins/apis/cds.py, eodag/plugins/apis/ecmwf.py, eodag/plugins/apis/usgs.py, eodag/plugins/authentication/aws_auth.py, eodag/plugins/authentication/header.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/oauth.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/search/base.py, eodag/plugins/search/creodias_s3.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/types/download_args.py, eodag/utils/__init__.py, eodag/utils/constraints.py, eodag/utils/exceptions.py, pyproject.toml, setup.cfg, tests/integration/test_core_search.py, tests/units/test_download_plugins.py
Type hints fixes and code refactoring. Going from 264 mypy errors to 94
=> fix: type hints related fixes and refactoring

docs/notebooks/api_user_guide/4_search.ipynb, eodag/api/core.py, eodag/resources/stac.yml, eodag/resources/stac_api.yml, eodag/rest/stac.py, tests/resources/ext_product_types_free_text_search.json, tests/units/test_core.py, tests/units/test_http_server.py
Implements server-mode free text search of collections https://github.com/stac-api-extensions/collection-search#free-text-search.
Uses updated [guess_product_type](https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.guess_product_type) method that now accepts `free_text_filter` and `intersect` parameters.
See updated examples on [how to guess a product type](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/4_search.html#Guess-a-product-type).
=> feat: server mode collections search

eodag/api/core.py, eodag/config.py, eodag/plugins/apis/usgs.py, eodag/plugins/authentication/qsauth.py, eodag/plugins/authentication/sas_auth.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/plugins/search/static_stac_search.py, eodag/resources/providers.yml, eodag/utils/__init__.py, eodag/utils/stac_reader.py, tests/context.py, tests/integration/test_core_config.py, tests/units/test_auth_plugins.py, tests/units/test_download_plugins.py, tests/units/test_http_server.py, tests/units/test_search_plugins.py, tests/units/test_utils.py
SSL Verification changes to plugins configuration and to the download and auth plugin code to pass the argument to whether allow verification while making request call or not. Also fixed the relevant unit test cases.
=> feat: configurable requests ssl_verify

eodag/api/core.py, eodag/plugins/apis/cds.py, eodag/plugins/search/base.py, eodag/rest/core.py, eodag/rest/server.py, eodag/rest/types/stac_queryables.py, tests/units/test_core.py, tests/units/test_http_server.py
- refactor: simplify list_queryables in api core
- feat: create a list_queryables in base search plugin
- feat: handle multiple search plugins per provider
- fix[server]: do not modify type of default queryables
- fix[server]: use `collection` and `id` instead of `collections` and `ids`
=> fix: queryables fixes + small refactor

eodag/resources/providers.yml
Add the missing `url` parameter in `sara` provider configuration
=> fix: add missing url in sara provider configuration

docs/notebooks/tutos/tuto_wekeo.ipynb, eodag/plugins/apis/usgs.py, eodag/plugins/download/aws.py, eodag/plugins/download/http.py, tests/units/test_download_plugins.py
Mark progress bar as completed (green in notebooks) even if total size is unknown:
- use `total=None` instead of `total=0` in `download` `progress_callback` parameters
=> fix: completed progress_callback with unknown total

eodag/plugins/apis/usgs.py, tests/context.py, tests/units/test_apis_plugins.py
If the file `~/.usgs` exists when EODAG is launched and it contains a revoked API key, then `usgs.api.login()` raises the exception `USGSError` (with message `AUTH_REVOKED: API key has been revoked, please logout and re-login.`). The file `~/.usgs` must be manually removed because calling `usgs.api.logout()` raises the same exception without removing it.
=> fix: re-login in UsgsApi plugin on api file error

setup.cfg
Fixes CI failures with `orjson` on python 3.12 for Windows:
```
[gw2] [ 10%] FAILED tests/units/test_metadata_mapping.py::TestMetadataFormatter::test_convert_interval_to_datetime_dict 
[...]
>       formated_dict = orjson.loads(formated.replace("'", '"'))
E       AttributeError: module 'orjson' has no attribute 'loads'
```
Pins `orjson` version following its [v3.10.0 release](https://github.com/ijl/orjson/releases/tag/3.10.0)
=> build: orjson pinned for windows py312

eodag/plugins/search/build_search_result.py, eodag/resources/providers.yml, tests/units/test_search_plugins.py
Fixes parsing issue for `orderLink` in `build_search` plugins
=> fix: orderLink in build_search plugins

eodag/plugins/download/http.py, pyproject.toml, setup.cfg
requests-ftp was only necessary for some wekeo product types and is not needed anymore with the new version of the wekeo API -> dependency removed
=> refactor: remove not needed anymore requests-ftp

eodag/plugins/download/http.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/qssearch.py, eodag/rest/core.py, eodag/rest/server.py, eodag/utils/__init__.py, tests/__init__.py, tests/context.py, tests/units/test_download_plugins.py, tests/units/test_http_server.py
When downloading an OFFLINE product in server mode:
- return HTTP Status 202 with new download link containing order status check information as query parameters
- don't retry to download the product again
Closes #871 
Also fixes missing `dataset` parameter after `BuildSearchResult` search-by-id in server mode
=> feat[server]: offline products order handling

eodag/rest/core.py, tests/units/test_http_server.py
In server mode, fixes missing order status query arguments in some case during new download-link generation
=> fix[server]: missing order status query args

eodag/types/__init__.py
Fixes test checking `FieldInfo` representation following `pydantic v2.7.0` release and `default` parameter inclusion if `None` and `required=False`.
See https://github.com/pydantic/pydantic/pull/8801
=> test: FieldInfo repr with pydantic >= 2.7.0

eodag/rest/core.py
In server mode, fixes authentication issue when downloading a product through an `Api` plugin
=> fix[server]: auth for download through Api plugins

eodag/api/core.py, tests/units/test_core.py
Iterate over all pages in [search_by_id](https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/4_search.html#id-and-provider) and if it returns more than one result, try filtering results using [crunch](https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/6_crunch.html#Filter-by-property) before failing
=> refactor: search all and crunch for _search_by_id 

eodag/api/core.py
Fixes unwanted log `No result could be obtained from any available provider` when search fails with specified provider
=> fix: search fallback error logging

README.rst
Fixes newlines between badges.
[Inline images](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image) usage following github rst rendering engine update.
See https://github.com/github/markup/issues/1801 and https://github.com/orgs/community/discussions/114690
=> docs: prevent newline between README badges

README.rst, docs/getting_started_guide/install.rst, docs/plugins_reference/auth.rst, docs/plugins_reference/download.rst, docs/plugins_reference/search.rst, eodag/api/core.py, eodag/plugins/manager.py, eodag/plugins/search/qssearch.py, eodag/rest/__init__.py, setup.cfg, tests/test_requirements.py, tests/units/test_core.py
Fixes #461 
Add new extras and move some required dependencies to optional dependencies.
This will make basic installation way lighter.
New available extras:
- `eodag[all]`, including everything that would be needed to run eodag and associated tutorials with all features
- `eodag[all-providers]`, including dependencies required to have all providers available
- `eodag[aws]`, including dependencies for plugins using Amazon S3
- `eodag[csw]`, including dependencies for plugins using CSW
- `eodag[ecmwf]`, including dependencies for `EcmwfApi`
- `eodag[usgs]`, including dependencies for `UsgsApi`
- `eodag[server]`, including dependencies for server-mode
=> build: refactor and new optional dependencies

eodag/plugins/apis/ecmwf.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/data_request_search.py, eodag/rest/stac.py, eodag/utils/__init__.py, tests/context.py
Moves `DEFAULT_MISSION_START_DATE` constant to `eodag.utils` (prevents `eodag.rest` import from client-mode)
=> fix: move DEFAULT_MISSION_START_DATE to utils

eodag/resources/providers.yml
Removes no-more-available `discover_product_types` for `creodias` (https://finder.creodias.eu/attributes.json no more available, and https://datahub.creodias.eu/stac/collections results differing from our configured search API)
=> fix: removes creodias discover_product_types

eodag/rest/utils/__init__.py, eodag/utils/rest.py
Moves shareable `eodag.rest.utils` functions to `eodag.utils.rest` that won't need `eodag[server]` installed.
Needed by https://github.com/CS-SI/eodag-labextension/pull/148
=> fix: shared rest functions without server extra

eodag/resources/stac.yml, eodag/rest/stac.py, tests/units/test_http_server.py
[order](https://github.com/stac-extensions/order) and [storage](https://github.com/stac-extensions/storage) STAC extensions usage in server-mode in order to return `EOProduct.properties["storageStatus"]` in server response
=> feat(server): order and storage extensions usage

eodag/api/product/_product.py
Catch  `EOProduct.location` resolve errors during download, when it contains incompatible special characters
=> fix: catch product.location resolve errors during download

eodag/rest/server.py, tests/units/test_http_server.py
Enable `HEAD` requests in server-mode
=> feat(server): enable HEAD requests

docker/stac-server.dockerfile, eodag/plugins/download/http.py, tests/units/test_download_plugins.py
raise an error when the download request to the provider returns an empty response
=> fix: handle empty response from provider

eodag/rest/stac.py, tests/units/test_http_server.py
provider is now added to "self" link in features of /items and /catalogs/.../items endpoints
=> fix(server): add provider in self link of item

eodag/rest/types/stac_queryables.py, eodag/types/__init__.py, tests/units/test_http_server.py
- type for queryables where Annotated is used in type is now also set in server mode
- new parameters for additional information from Annotated (min, max) created
=> fix(server): type missing on some queryables

eodag/api/product/metadata_mapping.py
Update templates detection in metadata-mapping, which will prevent having logs like:
```
WARNING: Could not parse foo (bar?{"baz":"qux"}) using product properties"
```
=> fix: update templates detection in metadata-mapping

eodag/api/product/metadata_mapping.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py
Updates  `metadata.mapping.format_query_params update()` signature in order to prevent issues with `product_type` query param (occured on some `ERA5_SL` / `wekeo`)
=> refactor: metadata.mapping format_query_params update

eodag/plugins/search/qssearch.py
Fixes `format_query_params` in `PostJsonSearch`, having issues following cross-merged PRs
=> fix: format_query_params in PostJsonSearch

setup.cfg
Fixes `orjson` requirement setting following https://github.com/CS-SI/eodag/pull/1079
=> fix: orjson requirement

setup.cfg
Fixes https://github.com/conda-forge/eodag-feedstock/issues/25
Install `uvicorn[standard]` in server mode. Fixes missing `watchfiles` dependency
=> build: uvicorn extras fix

setup.cfg
Fixes #1154 
Use `shapely >= 2.0.0` , as needed to be able to import `shapely.errors.GEOSException`
=> build: specify shapely min version

eodag/utils/constraints.py, eodag/utils/requests.py, tests/context.py, tests/units/test_http_server.py, tests/units/test_search_plugins.py, tests/units/test_utils.py
Refactors #1105 to make use of separated generic function `eodag.requests.fetch_json`
=> refactor: constraints fetch using fetch_json method

eodag/api/core.py, eodag/cli.py, eodag/config.py, eodag/plugins/manager.py, eodag/resources/stac.yml, eodag/rest/stac.py, tests/integration/test_core_search.py, tests/test_cli.py, tests/units/test_core.py
in EODAG library:
- add a `by_group` option on `core.available_providers`. If set, we return the unique list of groups instead of the list of provider names.
- update `list_product_types` to accept group name as provider names. Calling `list_product_types` with a group name set in the provider name will return the union of product types from all the providers of this group.
- update `get_search_plugin` to accept group names as provider names. Calling `get_search_plugin` with a group name as provider name will yield all the plugins belonging to the group.
in EODAG server:
- use group when set instead of provider name
> `group` is an optional field
Example:
I have 2 provider configuration in EODAG:
- earth_search
- earth_search_cog
I configure both with `group` **earth_search**.
=> feat: provider groups

eodag/rest/stac.py
This PR implements a quick fix for the PR #1008.
When looking for the external stac collection, the legacy `_id` was prioritized over the `ID` which is used when aliasing is used of a given collection.
=> fix: correct external stac collection id reference

eodag/resources/providers.yml
For some providers, the timeout in the configuration is lower than one of the provider's API. This PR adjust some of these values.
=> Adjust timeout to match the provider's one

eodag/rest/stac.py, tests/units/test_stac_utils.py
This PR provides an additional fix for the generation of a stac collection.
The links created by the stac config were erased when updating the dictionary contents, resulting in a 500 InternalServerError when trying to retrieve the list of collections if one of the collection was generated using an external stac collection.
=> fix: improve stac collection links generation

eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/resources/providers.yml, tests/units/test_auth_plugins.py
- Add support for the refresh token
- Use the expiration time of the access token and refresh token to determine if requesting a new token or using the already retrieved one
=> feat: add refresh token to `OIDCAuthorizationCodeFlowAuth` plugin

eodag/rest/stac.py, tests/units/test_stac_utils.py
In server mode, merge `providers` entry from external STAC collection.
Also ignores keywords formatting issues with a warning
=> fix(server): merge providers from external STAC collection

eodag/resources/providers.yml, eodag/rest/stac.py, tests/units/test_http_server.py
Use the provider group/name if no key prefix
=> Server additional props

eodag/rest/server.py
This PR proposes a fix for improving the responses sent to the user.
Currently, we respond 400 BadRequest for:
- Item searches of a collection that does not exist
- Item that does not exist in an existing collection
The response should explain to the user that their request was correct, but that such items do not exist, hence the `404 Not Found` 
Thanks!
=> fix(server): replace 400 with 404 when collection or item not found

eodag/api/product/_product.py, eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, tests/units/test_metadata_mapping.py
- Handles empty geometries on `creodias` and `cop_dataspace`
- Use `POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))` as default `EOProduct` geometry
=> fix: handle creodias and cop_dataspace empty geometries

eodag/resources/providers.yml, tests/units/test_core.py
Some `METOP` products could not have been search by id:
- `METOP_AVHRRL1` was missing in `eumetsat_ds` provider configuration
- `METOP_OSI_104` has an extension in its `id` that must have been kept
- `METOP_AVHRRGACR02` and `METOP_IASTHR011` have `+` characters in their `id` that must have been encoded
=> fix: eumetsat_ds METOP search by id

eodag/api/core.py, eodag/api/search_result.py, eodag/plugins/apis/ecmwf.py, eodag/plugins/apis/usgs.py, eodag/plugins/search/__init__.py, eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/creodias_s3.py, eodag/plugins/search/csw.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/plugins/search/static_stac_search.py, tests/context.py, tests/units/test_apis_plugins.py, tests/units/test_core.py, tests/units/test_search_plugins.py
Implements:
- `PreparedSearch`, an object collecting needed information for search
- `RawSearchResult`, an object representing a collection of raw/unparsed search results obtained from a provider.
This avoids storing search temporary data as plugin attributes
=> refactor: PreparedSearch and RawSearchResult usage

eodag/api/core.py, tests/units/test_core.py, tests/units/test_http_server.py
Add authentication object to search plugin when listing queryables with need_search enabled
=> fix(queryables): missing search plugin auth

eodag/plugins/download/http.py
Check if the user set `asset` in download `kwargs` so the `download_link` is not automatically used if the provider has `ignore_assets` attribute set to True in its configuration.
=> fix(server): single asset download with ignore_assets plugin setting

eodag/config.py, eodag/plugins/download/http.py, eodag/resources/providers.yml
needed for providers like dedt_lumi where auth should only be applied upon order
=> feat: allow no auth for download requests

.github/workflows/fetch.yml
Sorted keys in github action *fetch product types* diff summary
=> fix: sorted keys in gh action fetch product types diff

eodag/rest/config.py, eodag/rest/stac.py, tests/__init__.py, tests/units/test_http_server.py
Add a config to be able to hide from clients assets alternate origin URLs. Useful to hide backend URLs from EODAG server.
=> feat(server): add blacklist config for assets alt URLs

docs/getting_started_guide/install.rst, setup.cfg
Following #1108, restore `boto3` requirement to default installation and remove `[aws]` extra requirement
=> build: install boto3 by default

eodag/resources/providers.yml
Fixes `area` metadata mapping for `CAMS_EU_AIR_QUALITY_FORECAST` on `cop_ads`
=> fix(providers): area metadata mapping for CAMS_EU_AIR_QUALITY_FORECAST

eodag/api/core.py, eodag/resources/product_types.yml, eodag/resources/stac.yml, eodag/rest/core.py, eodag/rest/server.py, eodag/rest/stac.py, eodag/rest/types/stac_search.py, eodag/rest/utils/rfc3339.py, eodag/utils/rest.py, tests/units/test_core.py, tests/units/test_http_server.py, tests/units/test_stac_utils.py
- Add missionStartDate and missionEndDate filters in guess_product_types
- Add datetime filter in server /collections
=> feat(core): datetime filters in guess_product_types

eodag/plugins/authentication/openid_connect.py
Prevents conflicts between stored `token_info` in `OIDCRefreshTokenBase` plugins
=> fix(plugins): stored oidc token conflicts

eodag/api/core.py
fixes the way `pagination.max_items_per_page` is retrieved in search plugins in order to allow omitting `pagination` in configuration when not mandatory
=> fix(plugins): pagination is not globally mandatory

eodag/plugins/manager.py
Fixes #1233 
Adds missing `products` configuration in `Api` plugin download, when the `Api` plugin was not already retrieved through search (CLI mode)
=> fix(plugins): missing products conf in api plugin download

docs/conf.py, docs/plugins.rst, setup.cfg
- add a mock search plugin section to the documentation to describe further how to build a custom search plugin.
=> docs: mock search plugin section

eodag/api/product/_assets.py, eodag/api/product/_product.py, eodag/api/search_result.py, eodag/utils/repr.py, tests/units/test_eoproduct.py, tests/units/test_search_result.py
Implements HTML representation for `SearchResult`, `EOProduct`, `AssetsDict` and `Asset`, in order to enhance rendering in notebooks.
=> feat(core): SearchResult HTML representation

tests/test_end_to_end.py
Fix two end-to-end tests:
- search by id: it does not return a tuple anymore
- discover product types with `earth_search`: there are changes linked to endpoint new version of the provider
=> test: fix end-to-end tests

eodag/plugins/download/http.py, eodag/resources/providers.yml, tests/units/test_download_plugins.py
- The parameter `cacheable=true` in the `orderLink` causes a significant increase in the time needed for the product to become available. The parameter is removed in the provider `wekeo` in such cases.
- Fix `metadata_mapping` for the provider `wekeo` and `wekeo_cmems`
- Fix product order with JSON body containing a query string as value
=> fix(providers): remove cacheable param for wekeo order

eodag/api/core.py, eodag/plugins/search/static_stac_search.py, tests/integration/test_search_stac_static.py
If not specified in provider configuration, product-types discovery will be disabled by default when using `StaticStacSearch` plugin, in order to avoid using pre-configured and not adapted STAC API endpoint
=> fix(plugins): default disabled product-types discovery on StaticStacSearch

docs/plugins_reference/api.rst, docs/plugins_reference/auth.rst, docs/plugins_reference/crunch.rst, docs/plugins_reference/download.rst, docs/plugins_reference/search.rst
Following `sphinx 7.4.0` release and https://github.com/sphinx-doc/sphinx/pull/6792, remove current module from summarized items in documentation `autosummary` sections
=> docs: remove current module from summarized items

eodag/plugins/apis/usgs.py, eodag/resources/providers.yml, tests/units/test_apis_plugins.py
Fixes #1252
Implements lacking search-by-id mechanism on `UsgsApi` plugin for `usgs` provider
=> fix(providers): usgs search by id

eodag/plugins/authentication/aws_auth.py, eodag/plugins/download/aws.py, tests/units/test_auth_plugins.py
Fixes `AwsAuth` plugin to support `aws_session_token` credentials.
Updates types hints for this plugin
=> fix(plugins): aws_session_token support in aws_auth

eodag/plugins/download/http.py, tests/units/test_download_plugins.py
Fixes `HTTPDownload` HEAD requests check when downloading single asset, and adds the possibility to disable its SSL verification
=> fix(plugins): http asset HEAD check and ssl_verify

eodag/config.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/token.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/manager.py, eodag/plugins/search/__init__.py, eodag/plugins/search/cop_marine.py, eodag/plugins/search/qssearch.py, eodag/rest/core.py, eodag/rest/stac.py, eodag/rest/types/eodag_search.py, eodag/rest/types/queryables.py, eodag/rest/types/stac_search.py, eodag/types/__init__.py, eodag/types/download_args.py, eodag/utils/__init__.py, eodag/utils/notebook.py, eodag/utils/requests.py, eodag/utils/stac_reader.py, pyproject.toml, setup.cfg, tests/units/test_search_plugins.py, tox.ini
Fixes type hints and adds `mypy` check in `tox -e linters`
=> refactor: type hints fixes and mypy in tox

docs/notebooks/api_user_guide/4_search.ipynb, eodag/utils/__init__.py
Locations shapefile attributes are automatically converted to strings so integers like ids can be handled in search arguments:
```
locations=dict(entity_type=1234)
```
=> feat: handle integers as shapefile attributes

eodag/api/core.py, eodag/types/download_args.py
Fixes #1273
Enhance documentation for [`download()`](https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.download) and [`download_all()`](https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.download_all) keyword arguments that use [`DownloadConf`](https://eodag.readthedocs.io/en/latest/api_reference/types.html#eodag.types.download_args.DownloadConf) parameters.
=> docs(core): download kwargs

eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/token.py, eodag/plugins/authentication/token_exchange.py, eodag/resources/providers.yml, tests/units/test_auth_plugins.py
- add `ssl_verify` parameter to requests in `TokenAuth`, `OpenidConnect` and `KeycloakAuth`
- remove unnecessary `ssl_verify` config param from `GenericAuth`, `AwsAuth` and `HeaderAuth`
- also removes a few other unnecessary parameters
=> fix(plugins): add ssl_verify where necessary and remove where unnecessary

eodag/rest/stac.py, tests/units/test_stac_core.py
the path part of the "href" values of the assets is now quoted to avoid invalid characters in the urls, e.g. due to commas in the id which occur for some collections of the `eumetsat_ds` provider (`METOP_AVHRRGACR02` and `METOP_IASTHR011`)
=> fix(server): invalid characters in download urls

eodag/api/core.py, eodag/rest/core.py, tests/resources/ext_product_types_free_text_search.json, tests/units/test_core.py
all_collections cache hash does not include datetime filter
this PR also fixes the datetime filter to correctly handle open datetime intervals
=> fix(server): add datetime in collections cache hash

eodag/api/core.py
Adds missing `warning` level logs when an error occurs while [searching by id](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/4_search.html#id-and-provider) with `raise_errors=False`.
Related to #1291
=> fix(core): missing _search_by_id warning

eodag/plugins/search/qssearch.py, tests/integration/test_core_search.py
Fixes #1291 
Allows searching with [QueryStringSearch](https://eodag.readthedocs.io/en/latest/plugins_reference/generated/eodag.plugins.search.qssearch.QueryStringSearch.html) plugin with no `productType` specified
=> fix(plugins): qssearch without productType

eodag/plugins/search/qssearch.py
Skips parsing error if provider response cannot be read while discovering product types in `QueryStringSearch`
=> fix(plugins): skip product types discovery on parsing errors

setup.cfg
Enforce the use of shapely>=2.0.6 to fix issues with numpy 2.1 occurring with python 3.12.
Fixes #1302
=> fix(build): update shapely to fix issues with numpy 2.1

eodag/plugins/download/aws.py, tests/units/test_download_plugins.py
Handle correctly situations with aws plugin when no data to download is found on s3.
=> fix(plugins): raise error if no data available on AwsDownload

eodag/plugins/search/build_search_result.py, tests/units/test_search_plugins.py
When `end_date_excluded` was set to `false`, which is the case for `cop_cds` and `cop_ads`, invalid requests (`end_date < start_date`) were sent to the provider when the user entered the same start and end date. 
Also, when the user entered only a date and not a datetime, unexpected results were returned because the end date was reduced by one. 
With this fix, the end date is only reduced by one when the user enters a datetime with `00:00:00`. If only dates are given by the user, they are kept as they are.
=> fix(plugins): build_search_result end_date preprocessing

eodag/api/core.py, eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, tests/units/test_search_plugins.py
- Add mapping for parameter `hydrological_year` to provider `wekeo_ecmwf` and fix a typo in the `orderLink`
- Pass down the `_dc_qs` for the `PostJsonSearch` when downloading the product
- Manage leap years when calculating `hydrological_year`
Follow examples of queries and the generated `_dc_qs`. These tests can also be found in `tests.units.test_search_plugins.TestSearchPluginPostJsonSearch.test_plugins_search_postjsonsearch_query_params_wekeo`.
```bash
curl --location 'http://localhost:5000/search?provider=wekeo_ecmwf' --header 'Content-Type: application/json' --data '{
"collections": [
"GRIDDED_GLACIERS_MASS_CHANGE"
],
"limit": 10,
"page": 1,
"datetime": "1980-01-01T00:00:00Z/1981-12-31T23:59:59Z",
"query": {
"variable": {
"eq": "glacier_mass_change"
},
"format": {
"eq": "zip"
}, …
```
=> fix(providers): usage of `hydrological_year` in provider `wekeo_ecmwf`

eodag/rest/server.py
fix a bug that caused the server to be unavailable when a POST search request was processing
eodag search is a blocking function and does not support await
=> fix(server): send search_stac_items in its own threadpool

eodag/resources/providers.yml, eodag/rest/core.py, eodag/rest/types/eodag_search.py, tests/units/test_http_server.py
- adds the *provider* and `oseo` prefix to the `queryables` to match the parameters in the search result
- fix for the use of filter params with provider prefixes
- adds a per product type metadata mapping for the provider `eumetsat_ds` because the metadata mapping is used to create the queryables and they are different for different product types
=> fix(server): queryable issues and parameters prefixes

eodag/plugins/search/cop_marine.py, eodag/resources/product_types.yml, eodag/resources/providers.yml, tests/units/test_search_plugins.py
`cop_marine` provider fixes:
- if no date is given in the id of the product, the date given for the dataset the product belongs to is now used
- a mapping has been added to retrieve other information from the id (such as platform, analysis type) and to add it to the properties of the product
=> fix(providers): handle cop_marine in situ historical data

.github/workflows/deploy.yml, .github/workflows/fetch.yml, .github/workflows/test.yml, eodag/rest/types/eodag_search.py, eodag/utils/__init__.py
Adds missing `mypy` check in *linting* github action
=> ci: mypy in linting github action

eodag/api/core.py, eodag/plugins/manager.py, eodag/resources/providers.yml, tests/integration/test_core_search.py, tests/units/test_download_plugins.py
Following #1292
Fixes missing download authenticator when `downloadLink` is missing after a search (`cop_ads` and `cop_cds` providers which products are OFFLINE and orderable)
=> fix(core): download authentication without downloadLink

eodag/api/core.py, tests/test_end_to_end.py
Fixes issue with `wekeo_main` download authentication plugin matching:
Better compare `matching_url` with `orderLink` than `downloadLink` when product is `OFFLINE`
=> fix(core): better compare matching_url with orderLink when OFFLINE

docs/plugins_reference/auth.rst, eodag/plugins/manager.py, eodag/resources/providers.yml, tests/integration/test_core_search.py
Following #1292,
- Fixes `onda` authentication matching configuration.
- Fixes handling of [authentication plugins](https://eodag.readthedocs.io/en/latest/plugins_reference/auth.html) without _matching settings_: do not share them
=> fix(plugins): onda and no matching settings auth plugins

eodag/resources/product_types.yml, eodag/resources/providers.yml
- removes not needed metadata mappings for `wekeo_main` and `wekeo_ecmwf`
- solves #1328 but in a slightly different way than suggested:
`month` and `day` in the provider metadata mapping cannot be quoted because they are lists in most of the cases 
&rarr; added a product type specific metadata mapping for `ERA5_LAND` with quoted month instead
- also fixes the `missionStartDate` because `00:00` is not available for the first day
=> fix(providers): small errors in wekeo metadata mappings

eodag/plugins/download/http.py, eodag/rest/errors.py, tests/units/test_download_plugins.py, tests/units/test_http_server.py
Fix #1337 
When a `HttpDownload.order_download()` fails, the error is logged but this can easily go unnoticed by the user if logs aren't enabled. The purpose of this pull request is to raise an exception instead. 
However, this exception has a `status_code` attribute set to None, which makes the rest server crash when this status code is compared with integer values:
```
File "/home/al/venvs/dedl_lab/lib/python3.12/site-packages/starlette/responses.py", line 66, in init_headers
and not (self.status_code < 200 or self.status_code in (204, 304))
^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
This pull request provides a fix for that by ensuring that the status code defaults to 500.
=> fix(plugins): raise error when http download order fails

eodag/utils/exceptions.py, tests/units/test_utils_exceptions.py
Fixes issue with missing `Response` handling in `RequestError`.
This PR includes a test triggering the bug it's addressing. The issue was due to doing an `if` on a `Response` object to test the presence of that response object. But this response object evaluates to `False` if it doesn't have a status code 200. So instead we explicitly test that the response object is not `None`.
With this change, the exception triggered by the code example provided in #1339 should include the error message contained in the response from the provider:
```
eodag.utils.exceptions.RequestError: ('Skipping error while searching for dedl StacSearch instance', '{"description":"1 error(s). datetime: Value error, Invalid datetime range, must match format (begin_date, end_date)"}')
```
=> fix(utils): include response text in RequestError

.github/workflows/deploy.yml, .github/workflows/fetch.yml, .github/workflows/test.yml, CONTRIBUTING.rst, eodag/api/core.py, eodag/api/search_result.py, eodag/config.py, eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/qssearch.py, eodag/rest/config.py, eodag/rest/types/queryables.py, eodag/rest/types/stac_search.py, eodag/types/__init__.py, eodag/types/queryables.py, eodag/types/search_args.py, eodag/utils/__init__.py, eodag/utils/exceptions.py, setup.cfg, tests/test_requirements.py, tox.ini
- Adds `python3.13` support
- Drops `python3.8` support
- Adapts github actions to use `3.9` and `3.13` as min and max supported versions
=> build: add python3.13 and drop python3.8 support

.github/workflows/fetch.yml
fixes `fetch-product-types` CI job summary formatting in github actions
=> ci: fetch-product-types diff formatting

eodag/plugins/search/cop_marine.py, tests/units/test_search_plugins.py
improves the error handling at the request to fetch the product type information in `CopMarineSearch`:
- only use `UnsupportedProductType` exception in case of `NotFound` error code
- otherwise `RequestError` will be raised
=> fix(plugins): better error handling for cop_marine

eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, tests/test_end_to_end.py
Adds some fixes in `geodes` configuration for:
- search dates operators
- `thumbnail`/`quicklook` url
Adds missing end-to-end test for `geodes`.
Also logs `PostJsonSearch` query body as json.
=> fix(providers): geodes conf fixes

tests/test_end_to_end.py
Fix for `download()` expected output during end-to-end tests
=> tests: end-to-end tests download fix

setup.cfg, tox.ini
Force `tox` to use latest dependencies versions with command `uv pip install --upgrade {opts} {packages}`.
Needed because `uv` installed a very old `botocore` version (1.10.84) when running tests with tox and `python3.9`, which caused tests failure.
=> test: force deps upgrade on install in tox

.github/workflows/fetch.yml
`wekeo_main` credentials usage in github actions in order to fetch and add wekeo product types to external-product-types reference
=> ci: fetch wekeo product types

eodag/api/core.py
Shortened fetched product types logs
=> refactor(core): shorter fetched product types logs

eodag/plugins/search/cop_marine.py, tests/units/test_search_plugins.py
This PR fixes a problem with the ids of cop_marine products. If the filename of a product in the cop_marine s3 contained a "." somewhere in the middle (for example ids of product type MO_GLOBAL_MULTIYEAR_BGC_001_033), the id created from the filename was not correct (only the part until the "." was used). This is now fixed.
=> fix(plugins): cop_marine - handling of ids with points

eodag/plugins/download/http.py, tests/units/test_download_plugins.py
- So far if the download of one asset was failing, this was logged but no error was raised which hid problems during the download and could lead to incomplete or even empty results while the response was still 200. This is changed now so that the download is interrupted when a problem at the download of one asset occurs.
- After this change it became visible that for `planetary_computer` some assets where not downloaded because, for the same product, there are assets where authentication is required for the download and assets where authentication should not be added. 
&rarr; In `HTTPDownload`, the asset url is now compared to `matching_url` from the config to check if authentication should be added to the request.
=> fix(plugins): auth only when needed during http download

eodag/resources/providers.yml, tests/resources/wekeo_old_config.yml
Removes `two_passes_id_search` (old `wekeo` configuration parameter) from the `providers.yml` file because it is not used anymore
=> fix(providers): remove two_passes_id_search config param

eodag/plugins/download/base.py
Rename old (pre v3.x) record file to up-to-date format.
Fixes #1395
=> fix(core): rename old record file

eodag/plugins/download/http.py, eodag/utils/__init__.py, eodag/utils/exceptions.py, tests/units/test_download_plugins.py
Modify `order_download` and `order_download_status` methods from `HTTPDownload` plugin:
- Raise a `ValidationError` if response status code is `400`. Otherwise raise a `DownloadError` if any other error occured.
- Inherit `ValidationError` and `DownloadError` from `RequestError` to include provider's error in the description
=> fix(plugins): Validation error if 400 error during order

setup.cfg
This prevents an issue raised by `mypy` with `pydantic v2.10.0`.
`BaseModel.model_fields` return type is interpreted as `Callable[[BaseModel], dict[str, FieldInfo]]` instead of `dict[str, FieldInfo]`.
See https://github.com/pydantic/pydantic/issues/10907, a patch is expected soon and filtering `pydantic != 2.10.0` should be enough on our side.
=> build: prevent pydantic v2.10.0 usage

eodag/resources/product_types.yml, eodag/resources/providers.yml, tests/units/test_core.py
Bring back `FIRE_HISTORICAL` via `wekeo_ecmwf`, now with correct default values and start date.
=> fix(providers): FIRE_HISTORICAL on wekeo_ecmwf

charts/eodag-server/templates/deployment.yaml, eodag/cli.py, eodag/rest/server.py, eodag/rest/utils/__init__.py, eodag/utils/__init__.py, tests/units/test_http_server.py
At the moment we query / to ensure that the rest api is alive. This results in a lot of requests which can't be filtered out from the logs because we want to log requests to / coming from real users.
=> feat(server): add dedicated liveness endpoint

eodag/cli.py
Wrapped import in a try/except
=> fix(cli): handle import error of eodag.rest module

eodag/plugins/authentication/openid_connect.py
Compare only offset-aware datetimes in `openid_connect` auth plugins
=> fix(openid_connect): compare only offset-aware datetimes

setup.cfg
Use `PyJWT[crypto]` instead of `PyJWT` as dependency
=> build: add missing cryptography requirement

eodag/plugins/apis/usgs.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/rest/core.py, tests/units/test_download_plugins.py
Order and poll an `EOProduct` without downloading it, using `HTTPDownload.order()`.
Remaining to do in another PR:
- expose the method as `EOProduct.order()`
=> feat(plugins): order and poll without downloading

eodag/api/core.py, eodag/api/product/_product.py, eodag/plugins/apis/ecmwf.py, eodag/plugins/apis/usgs.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/utils/__init__.py
Update polling times:
- `DEFAULT_DOWNLOAD_WAIT` from 2 to 0.2 minutes (12s)
- `DEFAULT_DOWNLOAD_TIMEOUT` from 20 to 10 minutes
- typing changed from `int` to `float`
=> fix(core): polling times and typing update

eodag/resources/providers.yml
Use the new `identifier` property added by `geodes` as `id` in metadata mapping
=> fix(providers): geodes id property

eodag/utils/__init__.py
Adds `grib2` and `jp2` (lacking on windows) support to [eodag.utils.guess_extension](https://eodag.readthedocs.io/en/latest/api_reference/utils.html#eodag.utils.guess_extension) and  [eodag.utils.guess_file_type](https://eodag.readthedocs.io/en/latest/api_reference/utils.html#eodag.utils.guess_file_type) methods
=> feat(utils): update mimetypes definition

eodag/rest/core.py
eodag expects a string value for processingLevel
=> fix(server): load processing level as string in external stac collection

eodag/cli.py, eodag/config.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py
Typing fixes following `mypy 1.14.0` release
=> refactor: typing fixes following mypy 1.14.0

eodag/plugins/download/aws.py, eodag/plugins/download/creodias_s3.py, eodag/plugins/search/creodias_s3.py, tests/units/test_download_plugins.py, tests/units/test_search_plugins.py
If a product from `creodias_s3` was stored on the s3 in a `.tar` file with the path `bucket/../product_id.tar` instead of having the structure `bucket/../product_id/asset`, the search for a request for which the response includes such a product was failing.
`CreodiasS3Search` and `CreodiasS3Download` have now been adapted to consider this case.
=> fix(plugins): creodias_s3 search and download when no asset

docs/notebooks/tutos/tuto_cds.ipynb, docs/notebooks/tutos/tuto_ecmwf.ipynb, eodag/api/product/_product.py, eodag/plugins/download/base.py, eodag/plugins/download/http.py, eodag/resources/providers.yml, eodag/types/download_args.py, tests/__init__.py, tests/units/test_download_plugins.py, tests/units/test_eoproduct.py
=> fix(plugins): remove default HTTPDownload zip extension

eodag/plugins/search/build_search_result.py, eodag/resources/product_types.yml, eodag/resources/providers.yml
Fixes  #1446
Allow to list queryables of `SATELLITE_SEA_ICE_EDGE_TYPE` for `cop_cds` and `CAMS_EU_AIR_QUALITY_FORECAST` for `cop_ads` that did not work by correcting configurations.
Configuration of `NEMSAUTO_TCDC` for `meteoblue` is fixed but it is still impossible to list its queryables because the way they are discovered is not adapted for `meteoblue` metadata, as well as `NEMSGLOBAL_TCDC ` and all product types of `wekeo_ecmwf`. However, this issue will be solved in the PR #1427.
=> fix(providers): queryables fixes for some product-types

eodag/plugins/download/base.py, tests/integration/test_core_search_results.py
Do not retry downloading skipped products during `download_all`
=> fix(core): do not retry skipped products during download_all

eodag/plugins/crunch/filter_property.py, tests/integration/test_search_stac_static.py
Do not return product when the property is not found using [SearchResult.filter_property()](https://eodag.readthedocs.io/en/latest/api_reference/searchresult.html#eodag.api.search_result.SearchResult.filter_property) instead of cancelling crunch
=> fix(crunch): skip missing key in filter_property

eodag/resources/providers.yml
Fixes metadata-mapping for `geodes`:
- `title` also got from new `identifier` field (see #1441)
- `tileIdentifier` handles tiles beginning with a `T` or not (both happens)
- exclude potential `.xml` assets having `roles=[data]` for `downloadLink` mapping
=> fix(providers): geodes metadata mapping

eodag/resources/product_types.yml, eodag/resources/providers.yml
Adaptions in default values and mission start/end dates for `GLOFAS` and `EFAS` product types:
- changes the default values of `model` and `version` so that the earliest possible dates can be selected
- updates the values of `missionStartDate` and `missionEndDate`
=> fix(providers): default values and dates for GLOFAS and EFAS product types

eodag/api/product/metadata_mapping.py, eodag/plugins/search/build_search_result.py, eodag/resources/providers.yml, tests/units/test_search_plugins.py
- fix queryables, search and download of product types
- make search request more robust
- simplify config
- Fix https://github.com/CS-SI/eodag/issues/1452
=> fix(wekeo-ecmwf): correct queryables

eodag/resources/providers.yml, eodag/rest/stac.py
- include default datetime in `dedt_lumi` generated items
- in server-mode, remove `alias` and `productType` from item metadata
=> fix(server): add default datetime in dedt_lumi generated items

eodag/plugins/search/cop_marine.py, tests/units/test_search_plugins.py
The search by id for `cop_marine` was not working correctly for products which don't have a date in the id because at the creation of the result the date is parsed to get the start/end datetime which failed for those products. Now, the dataset dates are used in that case.
=> fix(cop_marine): search_by_id for products without date in id

eodag/utils/__init__.py
`geodes` items property `spatial:bbox` (string of tuple) was causing a parsing error in server mode
=> fix(server): geodes property parsing

eodag/api/core.py, eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, eodag/types/queryables.py, tests/units/test_core.py
The queryables with lower priority should not overwrite queryables from higher priority plugins.
=> feat(core): merge queryables by provider priority

eodag/api/product/metadata_mapping.py
Date parameters are returned as list value (with square brackets) instead of string.
This break the `_dc_qs` value for order requests in server mode.
This change in metadata_mapping was introduced for `wekeo` and is not needed anymore.
=> fix: metadata mapping for date parameter

eodag/plugins/download/http.py, tests/units/test_download_plugins.py
There were situations where in server mode the response at the download was empty but the response code was 200. 
This problem occurred when a zip was created and streamed and the download of the first file failed. In that case, the download was stopped, so the result was empty, but the `stream_zip` function was hiding the raised error from the user. This problem is now fixed, an error will be returned if the download fails.
=> fix(plugins): raise error on failed empty stream_zip

eodag/plugins/search/build_search_result.py
Fixes: #1476
Adds an implementation of `strip_quotes()` to dicts so that metadata mappings containing a dict (like `CAMS_SOLAR_RADIATION`) don't cause an error in the search (see referenced bug)
=> fix(plugins): ECMWFSearch strip_quotes implementation for dicts

eodag/resources/providers.yml
Fixes #1496
Adds `relativeOrbitNumber` queryable property in `geodes`.
Thanks [@LucHermitte](https://github.com/LucHermitte)!
=> fix(geodes): added relativeOrbitNumber property

docs/getting_started_guide/register.rst
Fixes a typo in [Geodes register](https://eodag.readthedocs.io/en/latest/getting_started_guide/register.html#geodes) link
=> docs: typo in geodes register link

eodag/plugins/download/aws.py, eodag/plugins/search/creodias_s3.py, tests/units/test_download_plugins.py
Adds `s3_endpoint` to `AwsDownload.get_rio_env`
=> fix(plugins): AWS rio_env s3_endpoint

eodag/plugins/search/build_search_result.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/utils/__init__.py, tests/context.py, tests/integration/test_core_config.py, tests/units/test_http_server.py, tests/units/test_search_plugins.py
Default providers search [timeout](https://eodag.readthedocs.io/en/stable/plugins.html#eodag.config.PluginConfig.timeout) from 5s to 20s
=> fix(providers): default search timeout to 20s

eodag/resources/providers.yml
Unquote searched numerical values on `geodes` provider:
- `orbitNumber`
- `relativeOrbitNumber`
- `cloudCover`
=> fix(geodes): unquote searched numerical values

eodag/api/product/_product.py, tests/units/test_eoproduct.py
The `get_quicklook` function is useful to preview products on an HMI, but for geodes provider the function returned an error because of a certificate problem. The parameter `ssl_verify` is `False` in the provider config but was not read in `get_quicklook`. This fixes the problem.
Fixes #1439
=> fix(core): ssl_verify setting for get_quicklook

eodag/plugins/search/build_search_result.py, tests/resources/form.json, tests/units/test_search_plugins.py
Fixes: #1450
When a queryable is called with an empty value (`""`, `None`, `[]`, etc.) in `dag.list_queryables()`, the returned default value of this queryable must be cleared in order to let other queryables depending on it list all their available values. Now, no default value is returned and the queryable appears as required.
Moreover, if a queryable was called in `dag.list_queryables()` while it was neither a default value of the provider configuration nor in the provider constraints file but it was in the provider queryables form, an error was raised. This is possible now.
`fetch_data()` method has been exposed instead of being initialized in `ECMWFSearch` class initialization to make the code cleaner and allow the mock of this method in tests.
=> fix(plugins): remove default queryables form value

eodag/api/product/metadata_mapping.py, tests/units/test_metadata_mapping.py
fixes the `convert_to_bounds()` method used in metadata mappings for `shapely.geometry.MultiPolygon` geometries
=> fix: convert_to_bounds for multipolygons

eodag/plugins/search/build_search_result.py, tests/units/test_search_plugins.py
fixes bugs that were causing the queryables for product type `CAMS_SOLAR_RADIATION` to fail with both providers (`cop_ads`, `wekeo_ecmwf`)
=> fix(plugins): small bugs in ecmwf queryables

eodag/resources/providers.yml
Based on feedback from Eumetsat that those parameters are static, all metadata mappings "eodag -> provider" for the `eumetsat_ds` provider except for `orbitNumber`, `startTimeFromAscendingNode` and `completionTimeFromAscendingNode` are removed.
So that they are not visible in the queryables anymore. If there is no mapping "provider -> eodag", the mapping is completely removed. 
`parentIdentifier` is kept although it is also static per product type because it is required in the request to `eumetsat_ds`.
=> fix(providers): remove unnecessary metadata mappings for eumtesat_ds

docs/api_reference/assets.rst, docs/api_reference/eoproduct.rst, docs/api_reference/exceptions.rst, docs/api_reference/index.rst, docs/api_reference/types.rst, docs/api_reference/utils.rst, docs/conf.py, docs/notebooks/api_user_guide/9_post_process.ipynb, eodag/api/product/_assets.py, eodag/api/product/_product.py, pytest.ini, setup.cfg
Include `eodag-cube`  code to [Python API Reference](https://eodag.readthedocs.io/en/latest/api_reference/index.html)
=> docs: eodag-cube api ref

eodag/resources/providers.yml
`wekeo` now offers only one dataset `EO:ESA:DAT:COP-DEM` for all `COP-DEM` products, so a filter by `providerProductType` has to be added to get the different product types; search by id is possible with the new dataset
=> fix(providers): update wekeo config for COP-DEM product types

setup.cfg
Remove some dependencies max versions that were temporary set to bypass issues
=> build: remove dependencies max versions

eodag/plugins/download/aws.py
Handle `InvalidRequest` in `AwsDownload`, that must be skipped during the authentication methods try loop
=> fix(plugins): handle InvalidRequest in AwsDownload

eodag/api/core.py, eodag/config.py, tests/integration/test_download_auth.py, tests/test_cli.py, tests/test_config.py, tests/units/test_core.py, tests/utils.py
Refactor the code to avoid using deprecated `pkg_resources`. See https://setuptools.pypa.io/en/latest/pkg_resources.html:
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.
=> refactor(core): replace deprecated pkg_resources

docs/getting_started_guide/register.rst, docs/notebooks/tutos/tuto_cds.ipynb
remove the -beta in the links in the documetation of `cop_ads` and `cop_cds`
=> docs: remove beta from ads and cds links

eodag/api/product/metadata_mapping.py, eodag/plugins/apis/ecmwf.py, eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/plugins/search/static_stac_search.py, eodag/resources/product_types.yml, eodag/resources/providers.yml, eodag/rest/stac.py, eodag/rest/types/queryables.py, eodag/utils/__init__.py, tests/units/test_core.py, tests/units/test_metadata_mapping.py, tests/units/test_search_plugins.py
This PR simplifies the configuration of `ECMWFSearch` products. 
- metadata mapping defined in the plugin are extended to cover all the common metadata mapping across `ECMWFSearch` providers
- remove the need of `"ecmwf:"` prefix in products configuration
- update config to always get datetime parameters from `datetime` filter in addition to ecmwf `day`, `month`, `year`
- change the date interval in case of missing end to be `start/start` instead of `start/start + 1d`. This is done to align the behavior of EODAG with the way ECMWF expects.
=> refactor(ecmwf): simplify ECMWFSearch configuration

eodag/plugins/apis/usgs.py, tests/units/test_apis_plugins.py
Prevents `FileNotFoundError` to be raised on `usgs` authentication attempt failure
=> fix(plugins): FileNotFoundError on usgs auth attempt failure

setup.cfg
Following #1485 , update `usgs` dependency to install from its github repository until a new version is released.
=> build: usgs last version from git repo

eodag/plugins/search/build_search_result.py, eodag/types/__init__.py, tests/units/test_http_server.py
Populate `required[]` in JSON schema even when the variable has a default value.
=> feat(queryables): keep required even with default values

eodag/plugins/search/build_search_result.py
A geometry is required with EODAG and the mapping was missing for ECMWFSearch providers.
=> fix(EcmwfSearch): map geometry metadata

docs/getting_started_guide/configure.rst, eodag/api/core.py, tests/resources/file_product_types_override.yml, tests/units/test_core.py
add `EODAG_PRODUCT_TYPES_CFG_FILE` environment variable to configure the path for the `product_types.yml` file
=> feat(core): add EODAG_PRODUCT_TYPES_CFG_FILE env var

CHANGES.rst, setup.cfg
Do not install `usgs` from its github repository. 
Same thing for `eodag-cube` in tutorials.
=> build: do not install usgs from git repo

eodag/plugins/download/aws.py, eodag/resources/providers.yml
If `ignore_assets` is set in `AwsDownload` configuration in order to download whole product using `downloadLink` instead of assets, allow single asset download if wanted.
Set `ignore_assets = True` in `geodes_s3` settings.
=> fix(plugins): AwsDownload with asset and ignore_assets

eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, tests/units/test_metadata_mapping.py
Sanitize products `title` from `eumetsat_ds` provider to avoid special characters in strings like `"W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-2-OCA--FD--x-x---x_C_EUMT_20250127140934_L2PF_OPE_20250127135000_20250127140000_N__C_0084_0000"`
=> fix(providers): sanitize eumetsat_ds titles

eodag/config.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, tests/context.py, tests/units/test_search_plugins.py
Do not guess assets keys from from their URL/href when inappropriate.
Set search plugin `asset_key_from_href` configuration parameter to `False` to bypass the guess.
=> feat(plugins): do not guess keys from href when inappropriate

eodag/resources/providers.yml, eodag/utils/__init__.py, tests/units/test_apis_plugins.py, tests/units/test_search_plugins.py
According to the STAC specification, a full datetime value is expected instead of just a date. This fix ensures compliance by correctly handling datetime values.
=> fix(core):  Ensure datetime format compliance with STAC specification

eodag/config.py, eodag/plugins/authentication/token.py, eodag/resources/providers.yml, tests/units/test_auth_plugins.py
So far the expiration time of an access token was not stored and checked in the `TokenAuth` plugin. This is now done, so that no token request is sent if there is already an existing, valid token. 
The corresponding configuration has to be set using the new parameter `token_expiration_key`, see [TokenAuth configuration](https://eodag.readthedocs.io/en/latest/plugins_reference/generated/eodag.plugins.authentication.token.TokenAuth.html). It has been added for the providers `wekeo_main`, `wekeo_ecmwf` and `eumetsat_ds`.
=> fix(plugins): check expiration time in token auth

eodag/api/search_result.py, tests/units/test_search_result.py
fix a bug that caused the errors list in SearchResult to not be reset between SearchResult instances.
=> fix(core): reset errors between SearchResult instances

eodag/plugins/search/base.py, tests/units/test_core.py
Restore queryables metadata that was removed when only a `provider` (no product type) was passed as argument of [list_queryables](https://eodag.readthedocs.io/en/latest/api_reference/core.html#eodag.api.core.EODataAccessGateway.list_queryables)
=> fix(core): provider queryables metadata

eodag/plugins/search/base.py, eodag/plugins/search/qssearch.py, eodag/rest/errors.py, eodag/types/queryables.py, tests/units/test_http_server.py
- Fixes empty queryables returned instead of guessing from metadata mapping
- Adds default queryables for `id` and `tileIdentifier`
=> fix(core): missing queryables from metadata-mapping

.github/workflows/test.yml
Token usage for coverage report publishing in PR comments, see https://github.com/insightsengineering/coverage-action.
Should fix coverage reports publishing errors for PRs coming from forks.
=> ci: token usage for coverage report publishing

eodag/resources/providers.yml
Fixes #1632 
Removes extension from `creodias` and `cop_dataspace` products `title` mapping, which caused already downloaded products not to be detected when the same download occurs again
=> fix(providers): creodias and cop_dataspace products title mapping

eodag/plugins/search/cop_marine.py, eodag/plugins/search/static_stac_search.py, tests/units/test_search_plugins.py
Make discovery of queryables possible for `cop_marine` by creating `discover_queryables()` method in `StaticStacSearch` search plugin.
Furthermore, it is now possible to search by geometry with this provider.
=> feat(plugins): add queryables to cop_marine

eodag/plugins/manager.py, setup.cfg, tests/integration/test_config_ext_plugin.py, tests/resources/fake_ext_plugin/eodag_fakeplugin.egg-info_/PKG-INFO, tests/resources/fake_ext_plugin/eodag_fakeplugin.egg-info_/SOURCES.txt, tests/resources/fake_ext_plugin/eodag_fakeplugin.egg-info_/entry_points.txt, tests/resources/fake_ext_plugin/eodag_fakeplugin.egg-info_/top_level.txt, tests/resources/fake_ext_plugin/pyproject.toml, tests/units/test_core.py
This PR replaces the use deprecated `pkg_resources` with `importilib.metadata`.
It fixes #1623 and resolve almost completely the issues reported in #1624.
Closes: #1623 
The solution uses the compatibility module `importlib_metadata` to support Python v3.9.
When you will decide to drop support for Python v3.9, that you should also be able to use the `importlib.metadata` directly from the standard library and remove the dependency from the external `importlib_metadata` package.
Thank you!
=> refactor(core): Use importlib.metadata instead of the deprecated pkg_resources

eodag/plugins/search/build_search_result.py, tests/units/test_search_plugins.py
The start & end time properties have been added to the result returned by `ECMWFSearch` when `year`, `month`, `day` are used in filters
=> fix(plugins): missing datetime properties in ECMWFSearch result

docs/notebooks/tutos/tuto_stac_client.ipynb, eodag/plugins/search/static_stac_search.py, eodag/utils/stac_reader.py
Restores custom text opener passed to `pystac` from `StaticStacSearch` that was not used any more.
Also updates documentation to mention that a STAC item can directly be a possible source for `StaticStacSearch` plugin.
=> fix(plugins): StaticStacSearch text opener

.github/workflows/deploy.yml, .github/workflows/publish.yml
Adds a new `Deploy if ready` workflow that triggers when changelog updates are merged into `develop`.
This workflow runs git merges, tag, and publish to pypi.
=> ci: automatic deployment

eodag/plugins/search/build_search_result.py, eodag/rest/core.py, tests/units/test_http_server.py
When we try to download an orderable item that isn't ready yet, we get an error. This PR fixes that. If "ORDERABLE" is in the link, we no longer search for the item—we directly order it.
=> fix(plugins): EcmwfSearch orderable products search

eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, tests/units/test_core.py
No longer force `additional_properties` to `True`.  Use `discover_metadata.auto_discovery` value from `providers.yml` instead. 
ref https://github.com/CS-SI/eodag/issues/1642
=> fix(plugins): adapt queryables additional_properties to providers config

eodag/plugins/search/build_search_result.py, eodag/plugins/search/cop_marine.py, tests/units/test_search_plugins.py
adds the product type alias to the product properties in the `ECMWFSearch` and `CopMarineSearch` plugin; This is required to use the alias for the download metrics of `opentelemetry-instrumentation-eodag`.
=> fix(plugins): add alias to properties in cop_marine and EcmwfSearch plugins

eodag/api/product/metadata_mapping.py, eodag/utils/__init__.py
If a search on a provider using `StacSearch` (e.g. `dedl`) was done using an array in the input for one or several of the query parameters (e.g. ` {"provider": "dedl", "productType": "SIS_HYDRO_MET_PROJ", "ecmwf:time_aggregation": ["annual_mean", "monthly_mean"]`), the search was failing due to a json parsing error. This has now been fixed by removing the quotes around arrays in the query string.
=> fix(core): remove quotes around arrays in query param

eodag/plugins/authentication/openid_connect.py, tests/units/test_auth_plugins.py
In this update, I introduced `try/except` blocks to some functions in the `openid_connect` file to enhance error handling and ensure the application handles exceptions better. 
I also added corresponding unit tests in the `test_auth_plugins` file to verify the new logic. 
Please note that the existing test: `test_all_requirements` is currently failing and will be addressed in a future update.
=> fix(plugins): openid_connect requests error handling (#1320)

eodag/plugins/search/qssearch.py, eodag/types/__init__.py, eodag/types/queryables.py, tests/units/test_search_plugins.py
This pull request fixes an issue where queryables were not matching correctly.
When the list of possible values contained only a single value, the dedl provider was returning an empty list instead of the expected single-item list.
=> fix(core): Queryables mismatch when list of possible values contains a single value

docs/getting_started_guide/configure.rst, docs/notebooks/api_user_guide/2_providers_products_available.ipynb
Describes [configuration environment variables](https://eodag.readthedocs.io/en/latest/getting_started_guide/configure.html#core-configuration-using-environment-variables) default values
=> docs: configuration environment variables defaults

eodag/config.py, eodag/plugins/authentication/token_exchange.py, eodag/plugins/manager.py, tests/__init__.py, tests/integration/test_core_config.py, tests/test_config.py, tests/units/test_download_plugins.py, tests/units/test_eoproduct.py, tests/units/test_utils_s3.py
Always validate (check if `type` is in config) before creating a `PluginConfig` object (validation added when using `.from_mapping`).
Also adds a more explicit warning if a malformed plugin is attempted to be loaded from an old user config file that has incorrect plugin topic keys (e.g. `auth` instead of `search_auth`, etc)
=> fix(core): always validate PluginConfig before loading

eodag/api/product/metadata_mapping.py, eodag/config.py, eodag/plugins/search/base.py, eodag/plugins/search/build_search_result.py, eodag/plugins/search/data_request_search.py, eodag/plugins/search/qssearch.py, eodag/resources/providers.yml, eodag/rest/errors.py, tests/units/test_search_plugins.py
Fixes #1531
For `MO_OCEANCOLOUR_GLO_BGC_L3_NRT_009_101` and `MO_OCEANCOLOUR_GLO_BGC_L4_NRT_009_102` product types, the range was not wide enought and only very recent products are available.
For `CLMS_CORINE`, `wekeo` does not accept date parameters but does not raise an error. Then, it has been handled in two steps:
- now `startTimeFromAscendingNode` and `completionTimeFromAscendingNode` are only mapped for this product type with this provider
- the keyword `raise_mtd_discovery_error` has been set up in `discover_metadata` configuration. It is a boolean parameter, and if it is instantiated  to `True` and the user searches a product type with a parameter not among the queryables of this product type, an error is raised before the search request. It would make sure that the user knows his …
=> fix(plugins): raise errors when metadata discovery is not allowed

eodag/config.py, eodag/plugins/authentication/keycloak.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/authentication/token.py, eodag/utils/__init__.py, tests/units/test_auth_plugins.py
A new configuration parameter, `token_expiration_margin` (default: 60 seconds), has been added to introduce a safety buffer that prevents authentication tokens from being rejected due to expiration occurring between the token's validity check and the actual request. 
This parameter was added to `config.py` and integrated into the `authentication` logic in both `eodag/plugins/authentication/token.py` and `eodag/plugins/authentication/openid_connect.py`, ensuring that token validity checks now consider this margin. 
Unit tests were also added to verify the correct behavior of this new logic. 
Fixes #1598
=> feat(plugins): auth token expiration margin

eodag/api/core.py, eodag/api/product/_product.py
Moves code that registers downloader after a search to a new method `EOProduct.register_downloader_from_manager`
=> refactor(core): register downloader using manager from search to EOProduct

docs/cli_user_guide.rst, eodag/cli.py, tests/test_cli.py
Uses [click command chaining](https://click.palletsprojects.com/en/stable/commands/#command-chaining) and allow user to chain `search` and `download` in a single command:
```sh
eodag search -p S2_MSI_L1C -s 2025-06-25 download
```
Reverts https://github.com/CS-SI/eodag/pull/1706
=> feat(cli): commands chaining

eodag/cli.py, tests/test_cli.py
Allows user to specify download directory using `--output-dir` option:
```sh
eodag download results.geojson --output-dir /path/to/downloads
```
See [CLI User Guide / Download](https://eodag.readthedocs.io/en/latest/cli_user_guide.html)
=> feat(cli): download output directory

eodag/cli.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/creodias_s3.py, eodag/plugins/download/http.py, eodag/rest/core.py, eodag/utils/__init__.py, eodag/utils/exceptions.py, eodag/utils/s3.py, tests/context.py, tests/units/test_download_plugins.py, tests/units/test_utils_s3.py
Optimize stream download for AWS plugin (used in server-mode)
- zip but do not compress
- multiple parallel download
- direct stream response to keep light memory pressure
- support multipart and zipped responses when downloading multiple files
- raw or zipped responses for single files
- support global range requests
- support download single files from remote zip archive
Download rate comparison when downloading a `S2_MSI_L1C` product on `creodias_s3`:
- before: 6,78 MB/s
- after: 19,3 MB/s (+184%)
=> perf(plugins): optimize AwsDownload streaming

eodag/cli.py, eodag/plugins/authentication/openid_connect.py, eodag/plugins/download/s3rest.py, eodag/plugins/search/qssearch.py, eodag/rest/core.py, eodag/utils/__init__.py, tests/context.py
Directly import `urllib.parse` methods instead of importing from utils.
`eodag.utils.merge_mapping` also lightly refactored.
=> refactor: directly import urllib.parse methods 

eodag/resources/providers.yml
Geodes now supports SSL verification, so we can set it in provider configuration and prevent the `InsecureRequestWarning` to display.
=> fix(providers): ssl verify for geodes

eodag/rest/stac.py
We added the host field directly in the retrieved STAC collection.
Because of that, we no longer need to add it manually, which previously caused a duplicate with the wrong value.
=> fix(server): remove duplicate host

NOTICE, eodag/plugins/download/http.py, eodag/rest/utils/__init__.py, eodag/utils/__init__.py, eodag/utils/s3.py, pyproject.toml, setup.cfg, tests/context.py, tests/units/test_download_plugins.py
Following https://github.com/CS-SI/eodag/discussions/1798,
[stream-zip](https://pypi.org/project/stream-zip) source code is no more available: https://github.com/uktrade/stream-zip
The author answer is:
> We're unable to provide more information due to Section 24 of FOIA.
> You can read more about Section 24 here: https://ico.org.uk/for-organisations/foi/freedom-of-information-and-environmental-information-regulations/section-24-safeguarding-national-security
This PR removes `stream-zip` dependency ant replaces it with [zipstream-ng](https://github.com/pR0Ps/zipstream-ng).
=> refactor: use zipstream-ng instead of stream-zip

eodag/config.py, eodag/plugins/apis/ecmwf.py, eodag/plugins/apis/usgs.py, eodag/plugins/authentication/aws_auth.py, eodag/plugins/authentication/base.py, eodag/plugins/base.py, eodag/plugins/download/aws.py, eodag/plugins/download/base.py, eodag/plugins/download/creodias_s3.py, eodag/plugins/download/http.py, eodag/plugins/download/s3rest.py, eodag/plugins/manager.py, eodag/plugins/search/__init__.py, eodag/plugins/search/base.py, eodag/plugins/search/creodias_s3.py, eodag/resources/providers.yml, eodag/types/__init__.py, eodag/utils/s3.py, tests/integration/test_core_search_results.py, tests/units/test_auth_plugins.py, tests/units/test_download_plugins.py, tests/units/test_search_plugins.py, tests/units/test_utils_s3.py
The `AwsAuth` plugin is refactored to actually perform the authentication on S3 and fetch the available objects:
- The `AwsAuth` plugin initializes the `s3_session` and `s3_resource` based on the available credentials.
- The method `do_authentication` has been renamed to `authenticate_objects` and moved to the `AwsAuth` plugin. Its sub-methods have also been moved or deleted because they were not necessary anymore due to simplification of the code.
- The s3 endpoint has been added to the config of the auth plugin.
=> refactor(plugins): move aws authentication methods to AwsAuth plugin

eodag/plugins/download/http.py, eodag/plugins/search/build_search_result.py
dedt_lumi respond with 400 when downloading an order that returns no data.
This PR improves the reported message to the user in such instance.
=> refactor(plugins): dedt_lumi not-available data error message

docs/_static/params_mapping_extra.csv, eodag/api/product/metadata_mapping.py, eodag/resources/providers.yml, eodag/resources/stac_provider.yml, tests/units/test_metadata_mapping.py
Fixes #1824 
In  order to align with [SAR STAC extension](https://github.com/stac-extensions/sar?tab=readme-ov-file#sarpolarizations), harmonize `polarizationChannels` values: 
- `SH` to `HH`
- `SV` to `VV`
- `DH` to `HH+HV`
- `DV` to `VV+VH`
- `VV VH` to `VV+VH`
- `VV&VH` to `VV+VH`
- `VV/VH` to `VV+VH`
- ... 
Unappropriate `polarizationMode` was also renamed to `polarizationChannels` for providers `aws_eos`, `peps`, and `sara`.
=> fix(providers): harmonize polarizationChannels property

eodag/resources/providers.yml
The mapping for `providerProductType` for `CLMS_CORINE` has changed on wekeo side, it is now the same as for the other collections.
=> fix(providers): CLMS_CORINE metadata mapping for wekeo

eodag/resources/providers.yml
Fixes #1859
Add '\\' to remove syntax error invalid escape sequence '\+'
=> fix(providers): polarizationChannels query escape

docs/conf.py, setup.cfg
Until we find how to fix/bypass these issues, pin `pydantic < 2.12.0` to prevent `sphinx` failures while building documentation:
```
WARNING: Failed guarded type import with TypeError("unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'")
WARNING: Failed guarded type import with ImportError("cannot import name 'AbstractSetIntStr' from 'pydantic._internal._utils' (/home/runner/work/eodag/eodag/.tox/docs/lib/python3.9/site-packages/pydantic/_internal/_utils.py)")
```
=> build: pin pydantic < 2.12.0 to prevent sphinx failures
