CS-SI/eodag

- docker-compose.yml
- docker/run-stac-server.sh
- docker/stac-browser.dockerfile
- docker/stac-server.dockerfile
created /docker folder in root directory for related files used in docker-compose.yml
> feat: add docker-compose for STAC server and browser

- eodag/api/core.py
> fix: locations should not be part of the kwargs passed to query

- tests/test_end_to_end.py
> Update the sobloo search of its end-to-end test

- eodag/api/product/metadata_mapping.py
- eodag/plugins/search/qssearch.py
- eodag/resources/stac_provider.yml
- eodag/utils/__init__.py
new pagination parameter added to providers configuration: `next_page_url_key_path`
It was needed for #190 , see https://github.com/CS-SI/eodag/pull/190#issuecomment-804173346 to enable pagination on some STAC providers
> feat: new pagination key next_page_url_key_path

- eodag/api/core.py
Missed that in https://github.com/CS-SI/eodag/pull/201
> Fix: missed to set limit=None in a whoosh query

- eodag/api/core.py
- tests/units/test_core.py
- tests/units/test_eoproduct.py
- tests/units/test_search_plugins.py
- tests/units/test_search_result.py
- tests/units/test_stac_reader.py
> Fix remove search kwargs when guessed

- eodag/plugins/download/base.py
> fix: download_all doesn't empty the passed list of products

- eodag/api/core.py
> Add a warning when searching with the non preferred provider

- eodag/plugins/download/base.py
- eodag/resources/user_conf_template.yml
- tests/units/test_eoproduct.py
> Fix auto extract

- eodag/api/core.py
- eodag/cli.py
- eodag/rest/stac.py
- eodag/rest/utils.py
> Fix: list_product_types doesn't return GENERIC_PRODUCT_TYPE anymore

- docs/getting_started_guide/register.rst
> docs: request an access to M2M API for usgs

- docs/notebooks/api_user_guide/1_overview.ipynb
- docs/notebooks/api_user_guide/2_providers_products_available.ipynb
- docs/notebooks/api_user_guide/4_search.ipynb
documentation update following GH-261
> docs: fix list_product_types output

- eodag/api/core.py
> fix: keyerror on search by id

- eodag/plugins/apis/usgs.py
- eodag/plugins/search/qssearch.py
> fix: more explicit message on  misconfigured auth

- eodag/resources/providers.yml
> feat: creodias metadata mapping update

- CHANGES.rst
- eodag/__meta__.py
> chore: bump version

- eodag/api/product/_product.py
- eodag/api/product/drivers/__init__.py
New drivers definition and loading mechanism, see https://github.com/CS-SI/eodag-cube/pull/17
> feat: EOProduct drivers definition update

- eodag/api/core.py
> fix: missing search_plugin when searching by id

- setup.py
> fix: update usgs to enable search_all

- eodag/__init__.py
- eodag/crunch.py
> API namespace

- docs/api_reference/searchresult.rst
- eodag/api/search_result.py
> Attach the crunchers directly to SearchResult

- eodag/api/core.py
- eodag/plugins/search/qssearch.py
- eodag/resources/providers.yml
- eodag/resources/stac_provider.yml
fixes #275 
POST requests instead of GET in `StacSearch`
> feat: POST reqs in StacSearch

- docs/api_reference/utils.rst
- eodag/api/core.py
- eodag/api/product/_product.py
- eodag/utils/__init__.py
- tests/__init__.py
- tests/integration/test_core_search_results.py
- tests/units/test_eoproduct.py
- tests/units/test_utils.py
> Revert "Download callback"

- eodag/plugins/apis/usgs.py
> fix: UsgsApi inheritance for download_all

- docs/api_reference/utils.rst
- eodag/api/core.py
- eodag/plugins/apis/base.py
- eodag/plugins/apis/usgs.py
- eodag/plugins/download/aws.py
- eodag/plugins/download/base.py
- eodag/plugins/download/http.py
- eodag/utils/__init__.py
- tests/__init__.py
- tests/context.py
- tests/integration/test_core_search_results.py
- tests/units/test_eoproduct.py
- tests/units/test_utils.py
Closes #121.
Correct implementation of #121 after reverting wrong one of PR #357.
> Download callback for download_all method

- docs/notebooks/api_user_guide/3_configuration.ipynb
> docs: fix broken link in documentation

- .github/workflows/test.yml
coverage reports using https://github.com/5monkeys/cobertura-action
> ci: coverage reports in gh actions

- docs/add_provider.rst
- docs/getting_started_guide/register.rst
Document how metada mapping is performed in https://eodag.readthedocs.io/en/latest/add_provider.html#parameters-mapping
> docs: metadata mapping documentation

- eodag/rest/utils.py
- tests/context.py
- tests/units/test_http_server.py
- tests/units/test_stac_utils.py
> STAC server use mapping for criterias from 'stac_provider.yml'

- eodag/api/core.py
- eodag/api/product/metadata_mapping.py
- eodag/plugins/search/qssearch.py
Enables STAC search on private servers needing auth for earch
> feat: auth on private stac search

- docs/notebooks/tutos/tuto_ship_detection.ipynb
> Fix shapefiles deadlink in sentinel-1 ship detection tutorial

- eodag/plugins/download/http.py
> Improve logs when a product is ordered

- eodag/api/core.py
- eodag/plugins/apis/base.py
- eodag/plugins/search/base.py
- eodag/plugins/search/csw.py
- eodag/plugins/search/qssearch.py
> Fix: clear search context

- docs/api_reference/searchresult.rst
- docs/notebooks/api_user_guide/4_search.ipynb
- eodag/api/search_result.py
- tests/units/test_search_result.py
Close #92 
Add to SearchResult:
- method `as_shapely_geometry_object()`
- method `as_wkt_object()`
> Add new SearchResult convertions

- docs/conf.py
Fixes #459 
See https://github.com/psf/requests/issues/6140#issuecomment-1135071992
> fix: requests intersphinx url

- CHANGES.rst
- pyproject.toml
> build: bump version

- CHANGES.rst
- eodag/plugins/download/aws.py
- eodag/resources/providers.yml
- eodag/resources/stac_provider.yml
- pyproject.toml
Fixes broken `AwsDownload` configuration for STAC providers
> fix: broken stac aws download conf

- eodag/plugins/apis/usgs.py
prevents error message with `usgs` provider:
```
USGSAuthExpiredError: API key has expired. Try logging out and logging back in.
```
> fix: logout and in if usgs apikey expires

- eodag/api/product/_product.py
- tests/units/test_eoproduct.py
> fix: id cast to str in progress_callback

- .gitignore
- tests/units/test_download_plugins.py
- tests/units/test_eoproduct.py
some more tests for download plugins
> test: download plugins

- eodag/api/core.py
Avoid search plugins build and optimizes product types list update after having fetched external product types configuration.
For more information on *product types discovery* and *external product types configuration*, see [online documentation](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/2_providers_products_available.html#Product-types-discovery).
> fix: do not build search plugins when updating product types list

- eodag/api/product/metadata_mapping.py
- eodag/plugins/search/qssearch.py
- eodag/rest/utils.py
- eodag/utils/__init__.py
Cache `jsonpath.parse()` using `functools` to enhance performance
> feat: cached jsonpath.parse

- eodag/api/product/_product.py
- eodag/plugins/download/base.py
- eodag/plugins/download/http.py
- setup.cfg
- tests/context.py
- tests/units/test_download_plugins.py
Refactorize [download retry mechanism](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/7_download.html?#Download-an-OFFLINE-product) and add tests
> refactor: download retry decorator and tests

- eodag/resources/providers.yml
Fixes #512 
Updates `creodias` authentication settings that changed recently
> fix: updated creodias auth settings

- tests/test_end_to_end.py
small update to end-to-end tests
> test: end-to-end tests update

- tests/test_cli.py
tests CLI version output
fixes #521
> test: cli version

- eodag/api/core.py
- tests/units/test_core.py
- tests/units/test_utils.py
> fix: accept all local files uri formats

- eodag/plugins/search/qssearch.py
- tests/context.py
- tests/units/test_core.py
> fix: request error handling during search_all

- eodag/plugins/download/http.py
- tests/units/test_download_plugins.py
Handle local assets when some (or all) are found using `HTTPDownload` plugin
> fix: handle local assets in HTTPDownload

- CONTRIBUTING.rst
- docs/cli_user_guide.rst
Fixes #501 and #536 (documentation typos)
> docs: fix cli examples and typos in contribute page

- eodag/plugins/download/http.py
- tests/units/test_download_plugins.py
fixes #564 
With descending priority, http asset size is now obtained from:
- HEAD header / Content-length
- HEAD header / content-disposition / size
- GET header / Content-length
- GET header / content-disposition / size
> feat: http asset size from get method

- tests/context.py
- tests/units/test_stac_reader.py
> test: read_local_json raises STACOpenerError

- eodag/api/product/_product.py
- tests/units/test_eoproduct.py
> fix: ignore percent vars resolve errors in register_downloader

- eodag/plugins/authentication/header.py
- eodag/plugins/authentication/openid_connect.py
- eodag/plugins/authentication/token.py
- tests/units/test_auth_plugins.py
Fixes #583 
Updates authentication plugins documentation and `TokenAuth` plugin requests error handling
> fix: update auth plugins docs and error handling

- docs/_static/params_mapping_extra.csv
- docs/_static/params_mapping_opensearch.csv
- docs/getting_started_guide/providers.rst
- docs/getting_started_guide/register.rst
- docs/index.rst
- docs/plugins.rst
- eodag/resources/user_conf_template.yml
- tests/test_end_to_end.py
Following #578, updates documentation and adds end-to-end test for `sara` provider
> docs: sara provider documentation

- eodag/plugins/search/qssearch.py
- tests/units/test_search_plugins.py
Fix in `PostJsonSearch._request` error handling and associated tests
> fix: PostJsonSearch request error and tests

- eodag/api/product/metadata_mapping.py
- tests/units/test_metadata_mapping.py
handle PostGIS [EWKT](https://postgis.net/docs/ST_AsEWKT.html) geometry format with new `MetadataFormatter.convert_from_ewkt()` and `MetadataFormatter.convert_to_ewkt()` methods
> feat: handle EWKT geometry format

- eodag/api/product/metadata_mapping.py
Fixes `discovery_config` usage in `metadata_mapping.properties_from_*()` methods
> fix: discovery_config in metadata_mapping

- eodag/resources/providers.yml
- tests/test_end_to_end.py
Following #623, restores creodias product types discovery using creodias STAC API
> fix: restore creodias product types discovery

- eodag/utils/__init__.py
Fixes #608 
Removes systematic [tqdm](https://github.com/tqdm/tqdm) progress bar refresh, and enables progress bar [refreshing customization](https://github.com/tqdm/tqdm#monitoring-thread-intervals-and-miniters)
> fix: progress bar adjustable refresh

- tests/test_end_to_end.py
- tests/units/test_core.py
end-to-end and core tests updates
> test: end-to-end and core tests updates

- eodag/resources/providers.yml
Fixes `meteoblue` download format
> fix: meteoblue download format

- eodag/plugins/authentication/token.py
- eodag/plugins/download/http.py
- eodag/plugins/download/s3rest.py
- eodag/resources/providers.yml
- eodag/utils/__init__.py
- tests/units/test_auth_plugins.py
- tests/units/test_download_plugins.py
Fixes #390 and #441
- advanced headers in `TokenAuth`
- `mundi` OFFLINE products order mechanism
> feat: mundi OFFLINE products order mechanism

- .github/workflows/deploy.yml
- .github/workflows/fetch.yml
- .github/workflows/test.yml
- eodag/plugins/download/http.py
- eodag/utils/__init__.py
- tests/integration/test_search_stac_static.py
- tests/units/test_stac_utils.py
Updates tests, code, and CI to remove warnings raised during tests or github actions
> fix: update tests, code, ci to remove warnings

- readthedocs.yml
Fixes #673
Updates readthedocs image following https://docs.readthedocs.io/en/stable/config-file/v2.html guidelines
> docs: update readthedocs img

- eodag/resources/providers.yml
Fixes #676 
Updates `peps` `storageStatus` property settings
> fix: peps storageStatus update

- eodag/plugins/apis/ecmwf.py
- tests/units/test_apis_plugins.py
In the same way as for #672, default dates usage with `EcmwfApi` (`ecmwf` provider), and refactored API plugin using `BuildPostSearchResult` plugin.
> fix: EcmwfApi default dates and refactor

- eodag/api/core.py
- tests/units/test_core.py
Fixes issue when updating external product types for unknown provider
> fix: update external product types for unknown provider

- eodag/plugins/search/qssearch.py
Fixes not-catched HTTP errors when running `fetch_product_types_list()`
> fix: urllib errors catch during search/discover

- eodag/api/core.py
Adds missing minimal pagination when searching by id
> fix: minimal pagination when searching by id

- eodag/rest/utils.py
Fixes broken links in STAC search items
> fix: items url through STAC search endpoint

- docker/stac-server.dockerfile
Updates EODAG install procedure in server dockerfile
> refactor: STAC server install in dockerfile

- eodag/plugins/crunch/filter_latest_intersect.py
Enables default search geom usage in [FilterLatestIntersect](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/6_crunch.html#Filter-the-latest-products-intersecting-a-geometry) crunch.
Needed in server mode for requests like http://127.0.0.1:5000/search?collections=S2_MSI_L1C&bbox=0,43,1,44&filter=latestIntersect
> fix: enable default search geom usage in FilterLatestIntersect crunch

- tests/units/test_http_server.py
more advanced STAC server tests
> test: advanced stac server tests

- docs/getting_started_guide/providers.rst
- eodag/resources/providers.yml
Updates some providers description
> docs: providers description update

- eodag/rest/utils.py
- tests/units/test_http_server.py
Fixes #768
Enable search using `ids` argument in STAC API search
> feat: server search by ids

- eodag/resources/providers.yml
`sara` provider configuration fix
> fix: sara provider conf

- eodag/api/product/metadata_mapping.py
- eodag/plugins/search/data_request_search.py
- eodag/plugins/search/qssearch.py
- eodag/resources/providers.yml
- tests/resources/provider_responses/s2l2a_productInfo.json
- tests/resources/provider_responses/s2l2a_tileInfo.json
- tests/units/test_core.py
- tests/units/test_search_plugins.py
Prevents product-type specific metadata-mapping from being applied to provider global metadata-mapping
> fix: product-type specific metadata-mapping

- eodag/rest/utils.py
- tests/units/test_http_server.py
- tests/units/test_stac_utils.py
Fixes server-mode issues with opened time intervals filtering
> fix(server): opened time intervals

- eodag/plugins/search/data_request_search.py
- eodag/resources/providers.yml
- tests/units/test_search_plugins.py
Default dates usage fix on `wekeo`
> fix: default dates on wekeo

- eodag/rest/stac.py
Code refactorization for "get STAC collection by id" in server mode
> refactor(server): get STAC collection by id

- eodag/plugins/download/session_http.py
- eodag/resources/nasa_providers.yml
New download plugin using a session that keeps the header in redirection
New providers for PODAAC, LARC_ASDC and OB_DAAC
The new download plugin inherits from the HTTPDownload plugin, the only change is that it is using a SessionWithHeaderRedirection session for performing requests, instead of a simple request.
The new providers should be added to the eodag user configuration.
> PODAAC plugin + provider

- eodag/api/core.py
- eodag/api/product/_product.py
- eodag/config.py
- eodag/plugins/manager.py
- eodag/rest/stac.py
- eodag/utils/__init__.py
- eodag/utils/notebook.py
- tests/__init__.py
in python3 all classes are "new-style" classes
> refactor: remove object inheritance

- eodag/plugins/search/qssearch.py
Fixes `StacSearch` default assets value
> fix: StacSearch default assets

- README.rst
- docs/stac_rest.rst
- eodag/api/core.py
- eodag/plugins/search/static_stac_search.py
- eodag/resources/stac.yml
- eodag/resources/stac_provider.yml
- tests/integration/test_core_config.py
- tests/resources/provider_responses/earth_search_search.json
- tests/units/test_http_server.py
- tests/units/test_search_plugins.py
> fix: removed deprecated server context extension

- eodag/api/core.py
- eodag/plugins/apis/cds.py
- eodag/plugins/search/build_search_result.py
- eodag/resources/stac.yml
- eodag/rest/server.py
- eodag/rest/stac.py
- eodag/rest/utils.py
- tests/units/test_http_server.py
Fixes server mode `CdsApi` dowloads using a new parameter `_dc_qs` to store query parameters
> fix(server): CdsApi download using _dc_qs parameter

- .gitignore
- README.rst
- docs/api_reference/core.rst
- docs/stac_rest.rst
- eodag/api/core.py
- eodag/cli.py
- eodag/plugins/apis/cds.py
- eodag/plugins/download/http.py
- eodag/plugins/search/build_search_result.py
- eodag/plugins/search/static_stac_search.py
- eodag/resources/providers.yml
- eodag/resources/stac.yml
- eodag/resources/stac_provider.yml
- eodag/rest/server.py
- eodag/rest/stac.py
- eodag/rest/utils.py
- tests/context.py
- tests/integration/test_core_config.py
- tests/resources/provider_responses/earth_search_search.json
- tests/units/test_apis_plugins.py
- tests/units/test_core.py
- tests/units/test_http_server.py
- tests/units/test_search_plugins.py
- tests/units/test_stac_utils.py
Update dedl with develop last commits
> Update dedl with develop last commits

- eodag/api/product/metadata_mapping.py
- eodag/plugins/download/http.py
- eodag/plugins/search/build_search_result.py
- eodag/plugins/search/data_request_build_search_result.py
- eodag/plugins/search/qssearch.py
- eodag/resources/product_types.yml
- eodag/resources/providers.yml
- eodag/resources/user_conf_template.yml
- eodag/rest/utils.py
- setup.cfg
- tests/units/test_core.py
- tests/units/test_http_server.py
- tests/units/test_search_plugins.py
- add new search plugin which is a mixture between data request search and build search result
- add config for polytope provider
- add test product type for polytope
> 924 polytope provider

- eodag/api/core.py
- eodag/api/product/metadata_mapping.py
- eodag/config.py
- eodag/plugins/apis/base.py
- eodag/plugins/search/qssearch.py
- eodag/utils/__init__.py
- tests/units/test_core.py
Several type-hints fixes, mainly adding `PluginConfig` internal parameters and their associated typing
> refactor: type hints fixes

- eodag/plugins/apis/cds.py
Do not try to extract date if it does not exist in query params
> fix[plugins/cds]: extract date from _dc_qs only if it exists

- docs/getting_started_guide/register.rst
- docs/notebooks/tutos/tuto_wekeo.ipynb
- eodag/resources/providers.yml
fixes #972 
Updates to new `wekeo-broker` api url
> fix: wekeo2 wekeo-broker api

- NOTICE
- eodag/rest/server.py
- eodag/utils/__init__.py
- setup.cfg
- tests/test_requirements.py
Adds missing requirements that were indirectly installed but not in `install_requires` yet
> build: add missing requirements

- CHANGES.rst
- README.rst
- charts/eodag-server/Chart.yaml
- docs/stac_rest.rst
- eodag/plugins/apis/base.py
- pyproject.toml
- tests/units/test_apis_plugins.py
> build: bump version to v2.12.1

- eodag/resources/providers.yml
Following https://code.visualstudio.com/updates/v1_87 and "*Sticky scroll is enabled by default in the editor*", add provider name as comment in `providers.yml` to help knowing the current position in this file.
See https://code.visualstudio.com/docs/getstarted/userinterface#_sticky-scroll
> docs: providers.yml comments for sticky scroll

- docs/notebooks/api_user_guide/4_search.ipynb
Fixes #1035 
Updated the documentation.
> docs: search dates documentation

- eodag/api/product/__init__.py
- eodag/api/product/_product.py
- eodag/plugins/apis/cds.py
- eodag/plugins/download/http.py
- eodag/plugins/search/creodias_s3.py
- pyproject.toml
Related to https://github.com/CS-SI/eodag-cube/pull/54
Fixes assets imports from `eodag-cube`
> fix: enable eodag-cube assets import

- docs/index.rst
- docs/plugins.rst
Update two documentation pages for new provider `wekeo_cmems`
> docs: add wekeo_cmems provider in index and plugins documentation pages

- eodag/rest/utils/__init__.py
* User entered a list and should get returned a list
> fix(server): next page bbox is a list

- eodag/resources/providers.yml
Adds missing `wekeo` pagination configuration
> fix: wekeo pagination

- eodag/resources/providers.yml
Fixes `CLMS*` product types search by id on `wekeo` provider
> fix: CLMS search by id on wekeo

- eodag/rest/types/eodag_search.py
> fix: allow str type for resolution param

- eodag/cli.py
Handles missing imports for server-mode when using CLI
> fix: server-mode imports handling in cli

- docs/conf.py
Updates https://eodag.readthedocs.io copyright date to 2024
> docs: rtd copyright 2024

- eodag/plugins/download/aws.py
- eodag/plugins/download/http.py
- eodag/plugins/download/s3rest.py
- tests/units/test_download_plugins.py
Allows configurable timeout for download plugins
> feat: configurable download timeout

- eodag/plugins/authentication/openid_connect.py
- tests/units/test_auth_plugins.py
Add tests for `OIDCAuthorizationCodeFlowAuth` plugin.
> test: `OIDCAuthorizationCodeFlowAuth` plugin

- eodag/plugins/authentication/token.py
Updates credentials check in `TokenAuth` plugin
> refactor: TokenAuth credentials check

- eodag/plugins/search/qssearch.py
- tests/units/test_search_plugins.py
Allows to use only one of `start`/`end` query parameters when searching on STAC providers
> feat: support opened time intervals for STAC providers

- eodag/resources/providers.yml
Fixes dates formatting on `EFAS_*` product types for `cop_cds`
> fix: EFAS dates formatting on cop_cds

- eodag/resources/stac.yml
- eodag/rest/stac.py
In server mode, fixes external STAC collections keywords mapping and empty values
> fix(server): stac ext collection keywords mapping

- eodag/rest/types/stac_queryables.py
- tests/units/test_http_server.py
- add bbox queryables
- remove none values in queryables properties
> feat(server): add bbox queryables

- eodag/api/core.py
- eodag/plugins/search/qssearch.py
- eodag/resources/providers.yml
- tests/units/test_search_plugins.py
Makes product type discovery for a single product configurable
> fix: single product type discovery

- eodag/rest/stac.py
- merge providers by group in collections
- use groups in items metadata (self link and assets)
> fix(server): merge providers by group & use groups in item links

- eodag/rest/core.py
required for the freetext search to work when only stacCollection is configured
> fix(server): append ext coll metadata to product_types config

- eodag/resources/product_types.yml
- eodag/resources/providers.yml
Fix provider's and product type's misconfiguration for `cop_ads`, `cop_cds`, and `wekeo`
> fix: providers and product-types conf update

- eodag/plugins/authentication/header.py
- tests/units/test_auth_plugins.py
`HTTPHeaderAuth` now accepts headers to be directly passed in credentials with an empty configuration:
```yaml
auth:
type: HTTPHeaderAuth
credentials:
X-API-Key: "XXX"
```
> feat: HTTPHeaderAuth accepts headers def in credentials

- eodag/plugins/search/cop_marine.py
fix issues with invalid dates and too large integers
> fix(plugins): CopMarine dates check

- CHANGES.rst
Updates `v3.0.0b1` changelog (missing features)
> docs: changelog update

- eodag/resources/providers.yml
- tests/units/test_core.py
GRIDDED_GLACIERS_MASS_CHANGE was only available with WEkEO.
> feat(providers): add GRIDDED_GLACIERS_MASS_CHANGE on provider cop_cds

- BREAKING_CHANGES.rst
- README.rst
- docs/api_reference/searchresult.rst
- docs/breaking_changes.rst
- docs/getting_started_guide/install.rst
- docs/index.rst
- eodag/api/core.py
- eodag/api/search_result.py
- setup.cfg
Document and highlight v3 breaking changes
> docs: v3 breaking changes

- eodag/cli.py
- eodag/rest/server.py
- eodag/utils/logging.py
- keep thread id only in server logs
- refactor `setup_logging` to reduce code redundancy
> refactor(server): logs format

- .github/workflows/test.yml
Update `actions/upload-artifact` to v4
> build(deps): update upload-artifact action v4

- eodag/resources/providers.yml
Fixes `yml` anchor issue in `wekeo` provider config introduced by #1258
> fix(wekeo): yml anchor issue in provider config

- eodag/resources/stac.yml
- eodag/rest/stac.py
- remove keywords with duplicate and None values
- merge summaries and remove None values
> fix(server): correct STAC collection generation

- eodag/api/core.py
- eodag/api/search_result.py
- eodag/plugins/apis/usgs.py
- eodag/plugins/authentication/generic.py
- eodag/plugins/authentication/openid_connect.py
- eodag/plugins/authentication/qsauth.py
- eodag/plugins/authentication/sas_auth.py
- eodag/plugins/authentication/token.py
- eodag/plugins/download/aws.py
- eodag/plugins/download/http.py
- eodag/plugins/download/s3rest.py
- eodag/plugins/search/build_search_result.py
- eodag/plugins/search/creodias_s3.py
- eodag/plugins/search/data_request_search.py
- eodag/plugins/search/qssearch.py
- eodag/rest/core.py
- eodag/rest/errors.py
- eodag/rest/server.py
- eodag/rest/types/eodag_search.py
- eodag/utils/exceptions.py
- eodag/utils/requests.py
- tests/context.py
- tests/units/test_auth_plugins.py
- tests/units/test_http_server.py
- tests/units/test_search_plugins.py
Improves search and authentication errors format :
- [include status_code in request errors when possible](https://github.com/CS-SI/eodag/pull/1237/commits/d0901457eb2e5672e55f12597820f781463df0ec)
- [method from_error() to generate RequestError](https://github.com/CS-SI/eodag/pull/1237/commits/2ef829cb857bdf3fdd2be84a0a3b8db5582ac491)
- [explode exception messages to different args](https://github.com/CS-SI/eodag/pull/1237/commits/b3a73eb98afe5da32fdfb4f93b77ca3d0264c0c2)
- [bind search errors to SearchResult instead of search plugin](https://github.com/CS-SI/eodag/pull/1237/commits/28e4e8ace7c15384c5f3d04d5793686b4f5a43bc)
- [[server]: use new ResponseSearchError to handle search result…](https://github.com/CS-SI/eodag/pull/1237/commits/2ce7776dfd8a5bc5274b9830bfd9459d49048379)
- …
> feat(core): improve search and authentication errors format

- .github/workflows/deploy.yml
- .github/workflows/fetch.yml
- .github/workflows/test.yml
- get_pypi_latest_version.sh
- pyproject.toml
- setup.cfg
- tox.ini
Speeds up tox tests and github actions CI using `uv` and `tox-uv`
> build: tests speedup using uv and tox-uv

- docs/tutos.rst
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
PR fixes the location of the `auxdata` directory in sources.
> docs: fixes tutos auxdata reference

- docs/notebooks/tutos/tuto_wekeo.ipynb
Updates WEkEO tutorial following #1292
> docs: updated wekeo tutorial

- eodag/plugins/download/base.py
- tests/units/test_download_plugins.py
Following #1396, add test for renamed old record files
> test: renamed old formatted record file

- eodag/config.py
- eodag/plugins/authentication/token.py
- tests/units/test_auth_plugins.py
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
Resolves issue https://github.com/CS-SI/eodag/issues/1449
> fix(plugins): distinct headers for token retrieve and authentication

- eodag/resources/providers.yml
Adds `tileIdentifier` queryable property for `geodes`
> fix(providers): geodes tileIdentifier

- eodag/plugins/download/http.py
- eodag/utils/__init__.py
Fixes conflict errors with existing files in download directory using `HTTPDownload`
> fix(plugins): HTTPDownload conflicting files

- BREAKING_CHANGES.rst
Small titles-related fixes in [Breaking Changes](https://eodag.readthedocs.io/en/latest/breaking_changes.html) documentation
> docs: titles fixes in Breaking Changes

- CHANGES.rst
- README.rst
- charts/eodag-server/Chart.yaml
- docs/stac_rest.rst
- pyproject.toml
> build: bump release

- eodag/resources/product_types.yml
- eodag/resources/providers.yml
- tests/units/test_core.py
removes 2 product types which exist twice with different ids and adds missing missionEndDates
> fix(providers): remove eumetsat_ds duplicate product types

- eodag/plugins/search/qssearch.py
Handle timeout errors coming from `urlopen` and raise `TimeOutError` with appropriate infos
> fix(plugins): urlopen timeout handling

- eodag/resources/providers.yml
Recognize geodes authentication errors during download
> fix(providers): recognize geodes auth errors during download

- .github/workflows/lint-pr-title.yml
Adds [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) to check PR titles
> ci: action-semantic-pull-request

- eodag/resources/providers.yml
Updates `geodes` and `geodes_s3` configuration following their API update. See https://geodes.cnes.fr/infos-ops/.
Fixes https://github.com/CS-SI/eodag/issues/1578
> fix(providers): geodes API update

- eodag/api/product/_assets.py
- tests/units/test_eoproduct.py
Fixes issue preventing to download an asset if special characters are in its key
> fix(core): download asset with special chars

- tests/units/test_apis_plugins.py
Fixed test sometimes failing for ecmwf dates following  #1573
> test: fixed test for ecmwf dates

- eodag/plugins/search/build_search_result.py
The datetime property has been added to the response to ensure compliance with the STAC specification.
> fix(plugins): add datetime for ecmwf search

- eodag/config.py
- eodag/plugins/authentication/token.py
- tests/units/test_auth_plugins.py
Fixes https://github.com/CS-SI/eodag/issues/1593
Thank you!
> fix(plugins): send client_id/client_secret with refresh_token in TokenAuth

- eodag/resources/providers.yml
adds a missing mapping for provider `cop_ewds`
> fix(providers): cop_ewds metadata mapping

- eodag/resources/providers.yml
Download link fix for `wekeo_main` products that need to be ordered
> fix(providers): wekeo_main orderable products download link

- eodag/plugins/download/base.py
- eodag/plugins/download/http.py
This PR aims to fix the _order_download_retry method.
> fix(plugins): order retry

- setup.cfg
Following https://github.com/CS-SI/eodag/pull/1552, updates `usgs` to its latest version now that it has been released
> build: update usgs to 0.3.6

- .github/workflows/deploy.yml
Use Personal Access Token for deploy github action
> ci: use personal access token for deploy github action

- docs/api_reference/core.rst
- eodag/api/core.py
- eodag/api/product/__init__.py
- eodag/api/search_result.py
- eodag/config.py
- eodag/plugins/search/qssearch.py
- eodag/utils/__init__.py
- tests/context.py
- tests/integration/test_core_search_results.py
- tests/resources/stac_singlefile.json
Import STAC items as `SearchResult` using new method `EODataAccessGateway.import_stac_items()`
> feat(core): import stac items as SearchResult

- docs/cli_user_guide.rst
- eodag/cli.py
- tests/test_cli.py
Download STAC items from their urls using `import_stac_items` method.
```sh
eodag download --stac-item https://example.com/stac/item1.json --stac-item /path/to/item2.json
```
> feat(cli): download STAC items from their urls

- eodag/plugins/download/base.py
- tests/__init__.py
- tests/units/test_download_plugins.py
Fixes #1713
Do not download again unextracted products
> fix(core): do not download again unextracted products

- eodag/config.py
- eodag/plugins/search/base.py
- eodag/plugins/search/qssearch.py
- eodag/resources/providers.yml
- tests/units/test_search_plugins.py
Fixed `metadata_mapping_from_product` mechanism, and use it in `wekeo_main`
> fix(plugins): metadata_mapping_from_product in search config

- eodag/resources/product_types.yml
- eodag/resources/providers.yml
- tests/units/test_core.py
add product types `MSG_CTH` and `MSG_CTH_IODC` to provider `eumetsat_ds`
> feat(providers): add 2 new MSG collections to provider `eumetsat_ds`

- eodag/api/product/metadata_mapping.py
- eodag/resources/stac_provider.yml
Format `instrument` from `list` to `str` for STAC providers
> fix(providers): instrument format for STAC providers

- tests/units/test_core.py
- tests/units/test_download_plugins.py
- tests/units/test_metadata_mapping.py
- tests/units/test_search_plugins.py
Updates #418
Adds more tests for parts of the code that were not covered yet.
> test: add more tests to improve coverage
